"""Country + visa metadata for We Hive backend.

Each country has multiple visa categories (Tourist, Business, Student, Work)
with per-category fees, validity, processing time and required documents.
This mirrors atlys.com's Indian-passport categorisation.
"""

from typing import List, Dict, Any


# Required-doc presets for reuse
DOCS_BASIC = ['Passport (6mo validity)', 'Passport-size photo']
DOCS_TOURIST = DOCS_BASIC + ['Bank statements (3 months)', 'Confirmed flight & hotel', 'Travel insurance']
DOCS_BUSINESS = DOCS_BASIC + ['Invitation letter', 'Bank statements (6 months)', 'Cover letter from employer', 'Business registration']
DOCS_STUDENT = DOCS_BASIC + ['University admit letter', 'Financial sponsor proof', 'Academic transcripts', 'Standardized test scores']
DOCS_WORK = DOCS_BASIC + ['Job offer letter', 'Employer sponsorship', 'Educational degrees', 'Police clearance']


def _vc(*, name, fees_inr, fees_usd, processing_days, validity, documents, multi_entry=True):
    return {
        'name': name,
        'fees_inr': fees_inr,
        'fees_usd': fees_usd,
        'processing_days': processing_days,
        'validity': validity,
        'documents': documents,
        'multi_entry': multi_entry,
    }


COUNTRIES: List[Dict[str, Any]] = [
    {
        'id': 'us', 'name': 'United States', 'flag': '\U0001F1FA\U0001F1F8',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student', 'Work'],
        'categories': {
            'Tourist': _vc(name='B1/B2 Visitor', fees_inr=15400, fees_usd=185, processing_days=42, validity='10 YEARS', documents=DOCS_TOURIST),
            'Business': _vc(name='B1 Business', fees_inr=15400, fees_usd=185, processing_days=42, validity='10 YEARS', documents=DOCS_BUSINESS),
            'Student': _vc(name='F-1 Student', fees_inr=29000, fees_usd=350, processing_days=60, validity='Course duration', documents=DOCS_STUDENT),
            'Work': _vc(name='H-1B / L-1', fees_inr=37800, fees_usd=460, processing_days=120, validity='3 YEARS', documents=DOCS_WORK),
        },
        'fees_usd': 185, 'validity': '10 YEARS',
        'delivery': {'standard_days': 35, 'rush_days': 14, 'same_day': False},
        'holiday_default_days': 10,
        'highlights': ['Highest demand', 'B1/B2 valid 10 years'],
    },
    {
        'id': 'uk', 'name': 'United Kingdom', 'flag': '\U0001F1EC\U0001F1E7',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student', 'Work'],
        'categories': {
            'Tourist': _vc(name='Standard Visitor', fees_inr=11400, fees_usd=140, processing_days=15, validity='6 MONTHS', documents=DOCS_TOURIST),
            'Business': _vc(name='Business Visitor', fees_inr=11400, fees_usd=140, processing_days=15, validity='6 MONTHS', documents=DOCS_BUSINESS),
            'Student': _vc(name='Student (Tier 4)', fees_inr=39000, fees_usd=470, processing_days=21, validity='Course duration', documents=DOCS_STUDENT),
            'Work': _vc(name='Skilled Worker', fees_inr=63000, fees_usd=760, processing_days=21, validity='5 YEARS', documents=DOCS_WORK),
        },
        'fees_usd': 140, 'validity': '6 MONTHS',
        'delivery': {'standard_days': 15, 'rush_days': 5, 'same_day': False},
        'holiday_default_days': 7,
        'highlights': ['Online application', 'Biometrics required'],
    },
    {
        'id': 'jp', 'name': 'Japan', 'flag': '\U0001F1EF\U0001F1F5',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student'],
        'categories': {
            'Tourist': _vc(name='eVisa Tourist', fees_inr=3700, fees_usd=45, processing_days=7, validity='90 DAYS', documents=DOCS_BASIC),
            'Business': _vc(name='Business eVisa', fees_inr=3700, fees_usd=45, processing_days=7, validity='90 DAYS', documents=DOCS_BUSINESS),
            'Student': _vc(name='Student Visa', fees_inr=22000, fees_usd=265, processing_days=30, validity='Course duration', documents=DOCS_STUDENT),
        },
        'fees_usd': 45, 'validity': '90 DAYS',
        'delivery': {'standard_days': 7, 'rush_days': 3, 'same_day': False},
        'holiday_default_days': 7,
        'highlights': ['eVisa available', 'Cherry blossom season'],
    },
    {
        'id': 'fr', 'name': 'France', 'flag': '\U0001F1EB\U0001F1F7',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student', 'Work'],
        'categories': {
            'Tourist': _vc(name='Schengen Short-Stay', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_TOURIST),
            'Business': _vc(name='Schengen Business', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_BUSINESS),
            'Student': _vc(name='Long Stay Student', fees_inr=8700, fees_usd=105, processing_days=21, validity='Course duration', documents=DOCS_STUDENT),
            'Work': _vc(name='Talent Passport', fees_inr=20800, fees_usd=250, processing_days=60, validity='4 YEARS', documents=DOCS_WORK),
        },
        'fees_usd': 95, 'validity': '90 DAYS',
        'delivery': {'standard_days': 12, 'rush_days': 5, 'same_day': False},
        'holiday_default_days': 7,
        'highlights': ['Schengen — 26 countries', 'Allows tourism + business'],
    },
    {
        'id': 'sg', 'name': 'Singapore', 'flag': '\U0001F1F8\U0001F1EC',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business'],
        'categories': {
            'Tourist': _vc(name='eVisa', fees_inr=2500, fees_usd=30, processing_days=4, validity='63 DAYS', documents=DOCS_BASIC),
            'Business': _vc(name='Business eVisa', fees_inr=2500, fees_usd=30, processing_days=4, validity='63 DAYS', documents=DOCS_BUSINESS),
        },
        'fees_usd': 30, 'validity': '63 DAYS',
        'delivery': {'standard_days': 4, 'rush_days': 2, 'same_day': True},
        'holiday_default_days': 5,
        'highlights': ['Same-day eVisa', 'No biometrics'],
    },
    {
        'id': 'ae', 'name': 'United Arab Emirates', 'flag': '\U0001F1E6\U0001F1EA',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business'],
        'categories': {
            'Tourist': _vc(name='30-Day eVisa', fees_inr=6700, fees_usd=80, processing_days=3, validity='60 DAYS', documents=DOCS_BASIC),
            'Business': _vc(name='Business eVisa', fees_inr=6700, fees_usd=80, processing_days=3, validity='60 DAYS', documents=DOCS_BUSINESS),
        },
        'fees_usd': 80, 'validity': '60 DAYS',
        'delivery': {'standard_days': 3, 'rush_days': 1, 'same_day': True},
        'holiday_default_days': 5,
        'highlights': ['Same-day available', 'No interview'],
    },
    {
        'id': 'au', 'name': 'Australia', 'flag': '\U0001F1E6\U0001F1FA',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student', 'Work'],
        'categories': {
            'Tourist': _vc(name='Visitor (subclass 600)', fees_inr=13300, fees_usd=160, processing_days=9, validity='12 MONTHS', documents=DOCS_TOURIST),
            'Business': _vc(name='Business Visitor', fees_inr=13300, fees_usd=160, processing_days=9, validity='12 MONTHS', documents=DOCS_BUSINESS),
            'Student': _vc(name='Subclass 500', fees_inr=58500, fees_usd=710, processing_days=30, validity='Course duration', documents=DOCS_STUDENT),
            'Work': _vc(name='TSS 482', fees_inr=99000, fees_usd=1200, processing_days=60, validity='4 YEARS', documents=DOCS_WORK),
        },
        'fees_usd': 160, 'validity': '12 MONTHS',
        'delivery': {'standard_days': 9, 'rush_days': 4, 'same_day': False},
        'holiday_default_days': 10,
        'highlights': ['Multi-entry', 'Online lodgement'],
    },
    {
        'id': 'ca', 'name': 'Canada', 'flag': '\U0001F1E8\U0001F1E6',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student', 'Work'],
        'categories': {
            'Tourist': _vc(name='Visitor (TRV)', fees_inr=10000, fees_usd=120, processing_days=14, validity='5 YEARS', documents=DOCS_TOURIST),
            'Business': _vc(name='Business Visitor', fees_inr=10000, fees_usd=120, processing_days=14, validity='5 YEARS', documents=DOCS_BUSINESS),
            'Student': _vc(name='Study Permit', fees_inr=12500, fees_usd=150, processing_days=45, validity='Course duration', documents=DOCS_STUDENT),
            'Work': _vc(name='Work Permit', fees_inr=12900, fees_usd=155, processing_days=60, validity='Up to 3 years', documents=DOCS_WORK),
        },
        'fees_usd': 120, 'validity': '5 YEARS',
        'delivery': {'standard_days': 14, 'rush_days': 7, 'same_day': False},
        'holiday_default_days': 8,
        'highlights': ['Multi-entry', 'Biometrics required'],
    },
    {
        'id': 'it', 'name': 'Italy', 'flag': '\U0001F1EE\U0001F1F9',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student'],
        'categories': {
            'Tourist': _vc(name='Schengen Short-Stay', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_TOURIST),
            'Business': _vc(name='Schengen Business', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_BUSINESS),
            'Student': _vc(name='National Student', fees_inr=4900, fees_usd=60, processing_days=30, validity='Course duration', documents=DOCS_STUDENT),
        },
        'fees_usd': 95, 'validity': '90 DAYS',
        'delivery': {'standard_days': 12, 'rush_days': 5, 'same_day': False},
        'holiday_default_days': 8,
        'highlights': ['Schengen', 'Heritage destination'],
    },
    {
        'id': 'ch', 'name': 'Switzerland', 'flag': '\U0001F1E8\U0001F1ED',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student'],
        'categories': {
            'Tourist': _vc(name='Schengen Short-Stay', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_TOURIST),
            'Business': _vc(name='Schengen Business', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_BUSINESS),
            'Student': _vc(name='National D-Visa', fees_inr=7900, fees_usd=95, processing_days=60, validity='Course duration', documents=DOCS_STUDENT),
        },
        'fees_usd': 95, 'validity': '90 DAYS',
        'delivery': {'standard_days': 12, 'rush_days': 5, 'same_day': False},
        'holiday_default_days': 7,
        'highlights': ['Alps', 'Schengen'],
    },
    {
        'id': 'th', 'name': 'Thailand', 'flag': '\U0001F1F9\U0001F1ED',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business'],
        'categories': {
            'Tourist': _vc(name='eVisa Tourist', fees_inr=3300, fees_usd=40, processing_days=5, validity='60 DAYS', documents=DOCS_BASIC),
            'Business': _vc(name='Business eVisa', fees_inr=8300, fees_usd=100, processing_days=10, validity='90 DAYS', documents=DOCS_BUSINESS),
        },
        'fees_usd': 40, 'validity': '60 DAYS',
        'delivery': {'standard_days': 5, 'rush_days': 2, 'same_day': True},
        'holiday_default_days': 6,
        'highlights': ['eVisa', 'Beaches & temples'],
    },
    {
        'id': 'de', 'name': 'Germany', 'flag': '\U0001F1E9\U0001F1EA',
        'visa_required': True, 'no_visa': False,
        'visa_types': ['Tourist', 'Business', 'Student', 'Work'],
        'categories': {
            'Tourist': _vc(name='Schengen Short-Stay', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_TOURIST),
            'Business': _vc(name='Schengen Business', fees_inr=7900, fees_usd=95, processing_days=12, validity='90 DAYS', documents=DOCS_BUSINESS),
            'Student': _vc(name='National Student', fees_inr=6300, fees_usd=75, processing_days=45, validity='Course duration', documents=DOCS_STUDENT),
            'Work': _vc(name='EU Blue Card', fees_inr=12500, fees_usd=150, processing_days=90, validity='4 YEARS', documents=DOCS_WORK),
        },
        'fees_usd': 95, 'validity': '90 DAYS',
        'delivery': {'standard_days': 12, 'rush_days': 5, 'same_day': False},
        'holiday_default_days': 7,
        'highlights': ['Schengen', 'Top student destination'],
    },
    {
        'id': 'np', 'name': 'Nepal', 'flag': '\U0001F1F3\U0001F1F5',
        'visa_required': False, 'no_visa': True,
        'visa_types': ['Tourist'],
        'categories': {
            'Tourist': _vc(name='Visa-Free Entry', fees_inr=0, fees_usd=0, processing_days=0, validity='150 DAYS', documents=['Passport (6mo validity)'], multi_entry=True),
        },
        'fees_usd': 0, 'validity': 'NOT REQUIRED',
        'delivery': {'standard_days': 0, 'rush_days': 0, 'same_day': True},
        'holiday_default_days': 5,
        'highlights': ['Visa-free for Indians', 'Mountains & culture'],
    },
    {
        'id': 'bt', 'name': 'Bhutan', 'flag': '\U0001F1E7\U0001F1F9',
        'visa_required': False, 'no_visa': True,
        'visa_types': ['Tourist'],
        'categories': {
            'Tourist': _vc(name='Permit (entry permit)', fees_inr=0, fees_usd=0, processing_days=0, validity='14 DAYS', documents=['Passport / Voter ID'], multi_entry=False),
        },
        'fees_usd': 0, 'validity': 'NOT REQUIRED',
        'delivery': {'standard_days': 0, 'rush_days': 0, 'same_day': True},
        'holiday_default_days': 6,
        'highlights': ['Permit on arrival', 'SDF applies'],
    },
]


# Holiday plans (rich data) — all 15 countries
HOLIDAY_PLANS: Dict[str, Dict[str, Any]] = {
    'us': {
        'best_time': 'May to October',
        'currency': 'USD',
        'language': 'English',
        'weather': 'Temperate, varies; Summer 25–35°C',
        'attractions': [
            {'id': 'a1', 'name': 'Statue of Liberty', 'city': 'New York'},
            {'id': 'a2', 'name': 'Grand Canyon', 'city': 'Arizona'},
            {'id': 'a3', 'name': 'Times Square', 'city': 'New York'},
            {'id': 'a4', 'name': 'Golden Gate Bridge', 'city': 'San Francisco'},
            {'id': 'a5', 'name': 'Walt Disney World', 'city': 'Orlando'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Land in NYC', 'desc': 'Check-in, walk Times Square, Brooklyn Bridge sunset.'},
            {'day': 2, 'title': 'Liberty + Wall Street', 'desc': 'Statue of Liberty ferry, Ellis Island, Wall Street.'},
            {'day': 3, 'title': 'Museums', 'desc': 'MoMA, Central Park, Top of the Rock.'},
            {'day': 4, 'title': 'Fly to Las Vegas', 'desc': 'Strip walk, Bellagio fountains, late-night show.'},
            {'day': 5, 'title': 'Grand Canyon', 'desc': 'Day trip to South Rim. Helicopter optional.'},
            {'day': 6, 'title': 'Fly to San Francisco', 'desc': 'Pier 39, Fisherman\'s Wharf, cable car.'},
            {'day': 7, 'title': 'Golden Gate', 'desc': 'Bike across Golden Gate, Alcatraz tour.'},
            {'day': 8, 'title': 'Yosemite day', 'desc': 'Day trip to Yosemite Valley.'},
            {'day': 9, 'title': 'LA + Hollywood', 'desc': 'Walk of Fame, Santa Monica pier.'},
            {'day': 10, 'title': 'Fly home', 'desc': 'Last brunch and depart.'},
        ],
    },
    'uk': {
        'best_time': 'May to September',
        'currency': 'GBP', 'language': 'English',
        'weather': 'Cool & rainy; Summer 18–25°C',
        'attractions': [
            {'id': 'a1', 'name': 'Big Ben & Parliament', 'city': 'London'},
            {'id': 'a2', 'name': 'Tower of London', 'city': 'London'},
            {'id': 'a3', 'name': 'Edinburgh Castle', 'city': 'Edinburgh'},
            {'id': 'a4', 'name': 'Stonehenge', 'city': 'Wiltshire'},
            {'id': 'a5', 'name': 'British Museum', 'city': 'London'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive London', 'desc': 'Westminster, London Eye, Thames cruise.'},
            {'day': 2, 'title': 'Royal London', 'desc': 'Buckingham Palace, Tower of London, Tower Bridge.'},
            {'day': 3, 'title': 'Museums', 'desc': 'British Museum, National Gallery, West End show.'},
            {'day': 4, 'title': 'Day trip Stonehenge', 'desc': 'Stonehenge, Bath Roman baths.'},
            {'day': 5, 'title': 'Train to Edinburgh', 'desc': 'Royal Mile, Edinburgh Castle.'},
            {'day': 6, 'title': 'Highlands', 'desc': 'Loch Ness day tour, whisky tasting.'},
            {'day': 7, 'title': 'Return London', 'desc': 'Camden, Notting Hill, fly out.'},
        ],
    },
    'jp': {
        'best_time': 'March–April (cherry blossoms) or October–November',
        'currency': 'JPY', 'language': 'Japanese',
        'weather': 'Mild; Spring 12–20°C',
        'attractions': [
            {'id': 'a1', 'name': 'Mount Fuji', 'city': 'Yamanashi'},
            {'id': 'a2', 'name': 'Senso-ji Temple', 'city': 'Tokyo'},
            {'id': 'a3', 'name': 'Fushimi Inari', 'city': 'Kyoto'},
            {'id': 'a4', 'name': 'Shibuya Crossing', 'city': 'Tokyo'},
            {'id': 'a5', 'name': 'Hiroshima Peace Park', 'city': 'Hiroshima'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Tokyo', 'desc': 'Shibuya, Shinjuku night walk.'},
            {'day': 2, 'title': 'Old Tokyo', 'desc': 'Asakusa, Senso-ji, Ueno Park.'},
            {'day': 3, 'title': 'Mt Fuji day trip', 'desc': 'Hakone, Lake Kawaguchiko.'},
            {'day': 4, 'title': 'Shinkansen to Kyoto', 'desc': 'Fushimi Inari shrine.'},
            {'day': 5, 'title': 'Kyoto temples', 'desc': 'Kinkaku-ji, Arashiyama bamboo grove.'},
            {'day': 6, 'title': 'Osaka day', 'desc': 'Dotonbori, Osaka Castle, street food.'},
            {'day': 7, 'title': 'Back to Tokyo', 'desc': 'Akihabara, Tokyo Tower.'},
        ],
    },
    'fr': {
        'best_time': 'April to October',
        'currency': 'EUR', 'language': 'French',
        'weather': 'Temperate; Spring 14–20°C',
        'attractions': [
            {'id': 'a1', 'name': 'Eiffel Tower', 'city': 'Paris'},
            {'id': 'a2', 'name': 'Louvre Museum', 'city': 'Paris'},
            {'id': 'a3', 'name': 'Palace of Versailles', 'city': 'Versailles'},
            {'id': 'a4', 'name': 'French Riviera', 'city': 'Nice'},
            {'id': 'a5', 'name': 'Mont Saint-Michel', 'city': 'Normandy'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Paris', 'desc': 'Seine cruise, Champs-Élysées.'},
            {'day': 2, 'title': 'Eiffel + Louvre', 'desc': 'Eiffel sunrise, Louvre afternoon.'},
            {'day': 3, 'title': 'Versailles', 'desc': 'Day trip to Versailles.'},
            {'day': 4, 'title': 'Train to Nice', 'desc': 'Promenade des Anglais.'},
            {'day': 5, 'title': 'Monaco day', 'desc': 'Casino, Old Town, Grand Prix circuit.'},
            {'day': 6, 'title': 'Provence', 'desc': 'Lavender fields, wine tasting.'},
            {'day': 7, 'title': 'Return Paris', 'desc': 'Montmartre, Sacré-Cœur.'},
        ],
    },
    'sg': {
        'best_time': 'February to April',
        'currency': 'SGD', 'language': 'English / Mandarin / Malay',
        'weather': 'Tropical; 26–32°C year-round',
        'attractions': [
            {'id': 'a1', 'name': 'Gardens by the Bay', 'city': 'Marina Bay'},
            {'id': 'a2', 'name': 'Marina Bay Sands', 'city': 'Marina Bay'},
            {'id': 'a3', 'name': 'Sentosa Island', 'city': 'Sentosa'},
            {'id': 'a4', 'name': 'Universal Studios', 'city': 'Sentosa'},
            {'id': 'a5', 'name': 'Hawker Centres', 'city': 'Chinatown'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Singapore', 'desc': 'Marina Bay walk, Merlion park.'},
            {'day': 2, 'title': 'Gardens & Sands', 'desc': 'Gardens by the Bay, Sands Skypark.'},
            {'day': 3, 'title': 'Sentosa', 'desc': 'Universal Studios, S.E.A. Aquarium.'},
            {'day': 4, 'title': 'Cultural districts', 'desc': 'Chinatown, Little India, Arab Street.'},
            {'day': 5, 'title': 'Depart', 'desc': 'Jewel Changi, fly out.'},
        ],
    },
    'ae': {
        'best_time': 'November to March',
        'currency': 'AED', 'language': 'Arabic / English',
        'weather': 'Desert; Winter 18–28°C, Summer 35–45°C',
        'attractions': [
            {'id': 'a1', 'name': 'Burj Khalifa', 'city': 'Dubai'},
            {'id': 'a2', 'name': 'Palm Jumeirah', 'city': 'Dubai'},
            {'id': 'a3', 'name': 'Sheikh Zayed Mosque', 'city': 'Abu Dhabi'},
            {'id': 'a4', 'name': 'Desert Safari', 'city': 'Dubai'},
            {'id': 'a5', 'name': 'Dubai Mall & Fountain', 'city': 'Dubai'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Dubai', 'desc': 'Dubai Marina walk, JBR Beach.'},
            {'day': 2, 'title': 'Burj + Mall', 'desc': 'Burj Khalifa observation, Dubai Mall.'},
            {'day': 3, 'title': 'Desert Safari', 'desc': 'Dune bashing, BBQ dinner.'},
            {'day': 4, 'title': 'Abu Dhabi day', 'desc': 'Sheikh Zayed Mosque, Louvre Abu Dhabi.'},
            {'day': 5, 'title': 'Depart', 'desc': 'Gold Souk, fly out.'},
        ],
    },
    'au': {
        'best_time': 'September to November',
        'currency': 'AUD', 'language': 'English',
        'weather': 'Diverse; Sydney 18–26°C in spring',
        'attractions': [
            {'id': 'a1', 'name': 'Sydney Opera House', 'city': 'Sydney'},
            {'id': 'a2', 'name': 'Great Barrier Reef', 'city': 'Cairns'},
            {'id': 'a3', 'name': 'Uluru', 'city': 'Northern Territory'},
            {'id': 'a4', 'name': 'Bondi Beach', 'city': 'Sydney'},
            {'id': 'a5', 'name': 'Great Ocean Road', 'city': 'Victoria'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Sydney', 'desc': 'Opera House, Circular Quay.'},
            {'day': 2, 'title': 'Bondi & Manly', 'desc': 'Beach hopping, ferry rides.'},
            {'day': 3, 'title': 'Blue Mountains', 'desc': 'Three Sisters lookout.'},
            {'day': 4, 'title': 'Fly to Cairns', 'desc': 'Reef snorkel cruise.'},
            {'day': 5, 'title': 'Daintree Rainforest', 'desc': 'River cruise, wildlife.'},
            {'day': 6, 'title': 'Fly to Melbourne', 'desc': 'Coffee culture, Federation Sq.'},
            {'day': 7, 'title': 'Great Ocean Road', 'desc': 'Twelve Apostles drive.'},
            {'day': 8, 'title': 'Phillip Island', 'desc': 'Penguin parade.'},
            {'day': 9, 'title': 'Sydney return', 'desc': 'Harbour Bridge climb.'},
            {'day': 10, 'title': 'Depart', 'desc': 'Last brunch, fly home.'},
        ],
    },
    'ca': {
        'best_time': 'June to September',
        'currency': 'CAD', 'language': 'English / French',
        'weather': 'Cold winters; Summer 18–26°C',
        'attractions': [
            {'id': 'a1', 'name': 'Niagara Falls', 'city': 'Ontario'},
            {'id': 'a2', 'name': 'Banff National Park', 'city': 'Alberta'},
            {'id': 'a3', 'name': 'CN Tower', 'city': 'Toronto'},
            {'id': 'a4', 'name': 'Old Quebec', 'city': 'Quebec City'},
            {'id': 'a5', 'name': 'Vancouver Stanley Park', 'city': 'Vancouver'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Toronto', 'desc': 'CN Tower, Distillery District.'},
            {'day': 2, 'title': 'Niagara Falls', 'desc': 'Hornblower cruise, falls illumination.'},
            {'day': 3, 'title': 'Fly to Calgary', 'desc': 'Drive to Banff via Bow Valley.'},
            {'day': 4, 'title': 'Lake Louise', 'desc': 'Canoe, Moraine Lake, Johnston Canyon.'},
            {'day': 5, 'title': 'Icefields Parkway', 'desc': 'Athabasca Glacier, Peyto Lake.'},
            {'day': 6, 'title': 'Fly to Vancouver', 'desc': 'Stanley Park, Granville Island.'},
            {'day': 7, 'title': 'Whistler day', 'desc': 'Sea-to-Sky Highway, Peak chairlift.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last harbour walk, fly home.'},
        ],
    },
    'it': {
        'best_time': 'April to June, September to October',
        'currency': 'EUR', 'language': 'Italian',
        'weather': 'Mediterranean; Spring 16–22°C',
        'attractions': [
            {'id': 'a1', 'name': 'Colosseum', 'city': 'Rome'},
            {'id': 'a2', 'name': 'Venice canals', 'city': 'Venice'},
            {'id': 'a3', 'name': 'Florence Duomo', 'city': 'Florence'},
            {'id': 'a4', 'name': 'Amalfi Coast', 'city': 'Salerno'},
            {'id': 'a5', 'name': 'Pompeii', 'city': 'Naples'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Rome', 'desc': 'Trevi Fountain, Spanish Steps.'},
            {'day': 2, 'title': 'Ancient Rome', 'desc': 'Colosseum, Roman Forum, Palatine Hill.'},
            {'day': 3, 'title': 'Vatican City', 'desc': 'St Peter\'s, Sistine Chapel.'},
            {'day': 4, 'title': 'Train to Florence', 'desc': 'Duomo, Uffizi.'},
            {'day': 5, 'title': 'Tuscany', 'desc': 'Wine tour, Siena.'},
            {'day': 6, 'title': 'Train to Venice', 'desc': 'Gondola ride, St Mark\'s.'},
            {'day': 7, 'title': 'Burano + Murano', 'desc': 'Colourful islands.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last gelato, fly home.'},
        ],
    },
    'ch': {
        'best_time': 'June to August (summer) or December–March (skiing)',
        'currency': 'CHF', 'language': 'German / French / Italian',
        'weather': 'Alpine; Summer 14–22°C',
        'attractions': [
            {'id': 'a1', 'name': 'Matterhorn', 'city': 'Zermatt'},
            {'id': 'a2', 'name': 'Lake Lucerne', 'city': 'Lucerne'},
            {'id': 'a3', 'name': 'Jungfraujoch', 'city': 'Bernese Oberland'},
            {'id': 'a4', 'name': 'Old Town Bern', 'city': 'Bern'},
            {'id': 'a5', 'name': 'Lake Geneva', 'city': 'Geneva'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Zurich', 'desc': 'Old Town, Lake Zurich cruise.'},
            {'day': 2, 'title': 'Lucerne', 'desc': 'Chapel Bridge, Mt Pilatus cable car.'},
            {'day': 3, 'title': 'Interlaken', 'desc': 'Two lakes, paragliding.'},
            {'day': 4, 'title': 'Jungfraujoch', 'desc': 'Top of Europe train.'},
            {'day': 5, 'title': 'Train to Zermatt', 'desc': 'Matterhorn views.'},
            {'day': 6, 'title': 'Glacier Express', 'desc': 'Zermatt to St Moritz.'},
            {'day': 7, 'title': 'Depart Zurich', 'desc': 'Last walk, fly home.'},
        ],
    },
    'th': {
        'best_time': 'November to February',
        'currency': 'THB', 'language': 'Thai',
        'weather': 'Tropical; Winter 22–32°C',
        'attractions': [
            {'id': 'a1', 'name': 'Grand Palace', 'city': 'Bangkok'},
            {'id': 'a2', 'name': 'Phi Phi Islands', 'city': 'Krabi'},
            {'id': 'a3', 'name': 'Phuket beaches', 'city': 'Phuket'},
            {'id': 'a4', 'name': 'Chiang Mai temples', 'city': 'Chiang Mai'},
            {'id': 'a5', 'name': 'Floating markets', 'city': 'Damnoen Saduak'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Bangkok', 'desc': 'Khao San Road, Wat Pho.'},
            {'day': 2, 'title': 'Grand Palace', 'desc': 'Wat Arun, river cruise.'},
            {'day': 3, 'title': 'Floating markets', 'desc': 'Damnoen Saduak day tour.'},
            {'day': 4, 'title': 'Fly to Phuket', 'desc': 'Patong, sunset on Promthep.'},
            {'day': 5, 'title': 'Phi Phi day', 'desc': 'Speedboat tour, snorkeling.'},
            {'day': 6, 'title': 'James Bond Island', 'desc': 'Phang Nga Bay tour.'},
        ],
    },
    'de': {
        'best_time': 'May to September',
        'currency': 'EUR', 'language': 'German',
        'weather': 'Cool & temperate; Summer 18–25°C',
        'attractions': [
            {'id': 'a1', 'name': 'Brandenburg Gate', 'city': 'Berlin'},
            {'id': 'a2', 'name': 'Neuschwanstein Castle', 'city': 'Bavaria'},
            {'id': 'a3', 'name': 'Cologne Cathedral', 'city': 'Cologne'},
            {'id': 'a4', 'name': 'Romantic Road', 'city': 'Rothenburg'},
            {'id': 'a5', 'name': 'Black Forest', 'city': 'Baden-Württemberg'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Berlin', 'desc': 'Brandenburg Gate, East Side Gallery.'},
            {'day': 2, 'title': 'WWII history', 'desc': 'Holocaust Memorial, Reichstag.'},
            {'day': 3, 'title': 'Train to Munich', 'desc': 'Marienplatz, beer hall dinner.'},
            {'day': 4, 'title': 'Neuschwanstein', 'desc': 'Castle day trip, Hohenschwangau.'},
            {'day': 5, 'title': 'Romantic Road', 'desc': 'Rothenburg ob der Tauber.'},
            {'day': 6, 'title': 'Black Forest', 'desc': 'Triberg, cuckoo clocks.'},
            {'day': 7, 'title': 'Frankfurt depart', 'desc': 'Old town, fly out.'},
        ],
    },
    'np': {
        'best_time': 'October to November or March to April',
        'currency': 'NPR', 'language': 'Nepali / English',
        'weather': 'Himalayan; Kathmandu 12–20°C in autumn',
        'attractions': [
            {'id': 'a1', 'name': 'Pashupatinath Temple', 'city': 'Kathmandu'},
            {'id': 'a2', 'name': 'Pokhara Lakeside', 'city': 'Pokhara'},
            {'id': 'a3', 'name': 'Annapurna Base Camp', 'city': 'Annapurna'},
            {'id': 'a4', 'name': 'Boudhanath Stupa', 'city': 'Kathmandu'},
            {'id': 'a5', 'name': 'Chitwan Safari', 'city': 'Chitwan'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Kathmandu', 'desc': 'Thamel walk, Pashupatinath evening aarti.'},
            {'day': 2, 'title': 'Heritage tour', 'desc': 'Boudhanath, Swayambhunath, Patan Durbar.'},
            {'day': 3, 'title': 'Drive to Pokhara', 'desc': 'Lakeside, World Peace Pagoda.'},
            {'day': 4, 'title': 'Sarangkot sunrise', 'desc': 'Annapurna range, paragliding.'},
            {'day': 5, 'title': 'Return Kathmandu', 'desc': 'Souvenir shopping, fly out.'},
        ],
    },
    'bt': {
        'best_time': 'October to December or March to May',
        'currency': 'BTN / INR', 'language': 'Dzongkha / English',
        'weather': 'Himalayan; Spring 8–20°C',
        'attractions': [
            {'id': 'a1', 'name': 'Tiger\'s Nest Monastery', 'city': 'Paro'},
            {'id': 'a2', 'name': 'Punakha Dzong', 'city': 'Punakha'},
            {'id': 'a3', 'name': 'Buddha Dordenma', 'city': 'Thimphu'},
            {'id': 'a4', 'name': 'Dochula Pass', 'city': 'Dochula'},
            {'id': 'a5', 'name': 'Phobjikha Valley', 'city': 'Wangdue'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Paro', 'desc': 'Drive to Thimphu, market visit.'},
            {'day': 2, 'title': 'Thimphu sights', 'desc': 'Buddha Dordenma, Memorial Chorten.'},
            {'day': 3, 'title': 'Dochula to Punakha', 'desc': 'Punakha Dzong at confluence.'},
            {'day': 4, 'title': 'Phobjikha Valley', 'desc': 'Crane sanctuary, Gangtey monastery.'},
            {'day': 5, 'title': 'Return to Paro', 'desc': 'Rinpung Dzong, hot stone bath.'},
            {'day': 6, 'title': 'Tiger\'s Nest hike', 'desc': 'Day hike to Taktsang monastery, fly home.'},
        ],
    },
    'mv': {
        'best_time': 'November to April',
        'currency': 'MVR', 'language': 'Dhivehi / English',
        'weather': 'Tropical; Winter 26–30°C',
        'attractions': [
            {'id': 'a1', 'name': 'Veligandu Atoll', 'city': 'North Malé'},
            {'id': 'a2', 'name': 'Maafushi Island', 'city': 'Maafushi'},
            {'id': 'a3', 'name': 'Maldives Underwater Restaurant', 'city': 'North Malé'},
            {'id': 'a4', 'name': 'Whale Shark Point', 'city': 'South Ari'},
            {'id': 'a5', 'name': 'Bikini Beach', 'city': 'Hulhumalé'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Male', 'desc': 'Transfer to resort, sunset dolphin cruise.'},
            {'day': 2, 'title': 'Snorkeling', 'desc': 'Coral reef snorkeling, manta ray encounter.'},
            {'day': 3, 'title': 'Island hopping', 'desc': 'Visit local islands, local lunch.'},
            {'day': 4, 'title': 'Water sports', 'desc': 'Jet ski, parasailing, kayaking.'},
            {'day': 5, 'title': 'Spa day', 'desc': 'Overwater spa treatment, private dining.'},
            {'day': 6, 'title': 'Departure', 'desc': 'Last swim, transfer to airport.'},
        ],
    },
    'id': {
        'best_time': 'April to October',
        'currency': 'IDR', 'language': 'Indonesian / English',
        'weather': 'Tropical; Summer 25–32°C',
        'attractions': [
            {'id': 'a1', 'name': 'Tanah Lot Temple', 'city': 'Bali'},
            {'id': 'a2', 'name': 'Ubud Monkey Forest', 'city': 'Ubud'},
            {'id': 'a3', 'name': 'Uluwatu Sunset', 'city': 'Bali'},
            {'id': 'a4', 'name': 'Mount Batur Sunrise', 'city': 'Kintamani'},
            {'id': 'a5', 'name': 'Nusa Penida Island', 'city': 'Bali'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Bali', 'desc': 'Kuta Beach, sunset beach dinner.'},
            {'day': 2, 'title': 'Ubud tour', 'desc': 'Rice terraces, Monkey Forest, Ubud Palace.'},
            {'day': 3, 'title': 'Mt Batur sunrise', 'desc': 'Early hike, hot springs, coffee plantation.'},
            {'day': 4, 'title': 'Uluwatu + Jimbaran', 'desc': 'Temple sunset, Kecak dance, seafood dinner.'},
            {'day': 5, 'title': 'Nusa Penida', 'desc': 'Crystal Bay, Angel\'s Billabong, Kelingking.'},
            {'day': 6, 'title': 'Seminyak', 'desc': 'Beach club, shopping, spa.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last surf session, fly home.'},
        ],
    },
    'lk': {
        'best_time': 'December to March',
        'currency': 'LKR', 'language': 'Sinhala / Tamil / English',
        'weather': 'Tropical; Winter 24–30°C',
        'attractions': [
            {'id': 'a1', 'name': 'Sigiriya Rock Fortress', 'city': 'Central'},
            {'id': 'a2', 'name': 'Temple of the Tooth', 'city': 'Kandy'},
            {'id': 'a3', 'name': 'Galle Fort', 'city': 'Galle'},
            {'id': 'a4', 'name': 'Yala National Park', 'city': 'Hambantota'},
            {'id': 'a5', 'name': 'Mirissa Beach', 'city': 'Matara'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Colombo', 'desc': 'Gangaramaya Temple, Galle Face Green.'},
            {'day': 2, 'title': 'Drive to Sigiriya', 'desc': 'Lion Rock climb, village tour.'},
            {'day': 3, 'title': 'Polonnaruwa ruins', 'desc': 'Ancient city, Minneriya safari.'},
            {'day': 4, 'title': 'Kandy', 'desc': 'Temple of Tooth, Kandy Lake, cultural show.'},
            {'day': 5, 'title': 'Nuwara Eliya', 'desc': 'Tea plantations, Gregory Lake.'},
            {'day': 6, 'title': 'Ella', 'desc': 'Nine Arch Bridge, Little Adam\'s Peak.'},
            {'day': 7, 'title': 'Galle', 'desc': 'Fort, beach, whale watching.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Mirissa beach, fly home.'},
        ],
    },
    'my': {
        'best_time': 'March to October',
        'currency': 'MYR', 'language': 'Malay / English',
        'weather': 'Tropical; Summer 26–33°C',
        'attractions': [
            {'id': 'a1', 'name': 'Petronas Towers', 'city': 'Kuala Lumpur'},
            {'id': 'a2', 'name': 'Langkawi Beach', 'city': 'Langkawi'},
            {'id': 'a3', 'name': 'Penang Street Food', 'city': 'George Town'},
            {'id': 'a4', 'name': 'Mount Kinabalu', 'city': 'Sabah'},
            {'id': 'a5', 'name': 'Cameron Highlands', 'city': 'Pahang'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive KL', 'desc': 'Petronas Towers, Jalan Alor food street.'},
            {'day': 2, 'title': 'KL sightseeing', 'desc': 'Batu Caves, National Mosque, Central Market.'},
            {'day': 3, 'title': 'Cameron Highlands', 'desc': 'Tea plantations, strawberry farm.'},
            {'day': 4, 'title': 'Penang', 'desc': 'George Town, street art, char kway teow.'},
            {'day': 5, 'title': 'Fly to Langkawi', 'desc': 'Cable car, sky bridge, beach.'},
            {'day': 6, 'title': 'Depart', 'desc': 'Last beach time, duty-free shopping.'},
        ],
    },
    'vn': {
        'best_time': 'February to April',
        'currency': 'VND', 'language': 'Vietnamese / English',
        'weather': 'Spring; North 20–28°C',
        'attractions': [
            {'id': 'a1', 'name': 'Ha Long Bay', 'city': 'Quang Ninh'},
            {'id': 'a2', 'name': 'Hoi An Ancient Town', 'city': 'Da Nang'},
            {'id': 'a3', 'name': 'Cu Chi Tunnels', 'city': 'Ho Chi Minh'},
            {'id': 'a4', 'name': 'Sapa Rice Terraces', 'city': 'Lao Cai'},
            {'id': 'a5', 'name': 'Mekong Delta', 'city': 'Can Tho'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Ho Chi Minh', 'desc': 'Ben Thanh market, street food tour.'},
            {'day': 2, 'title': 'Cu Chi + City', 'desc': 'Tunnels, Notre Dame, Reunification Palace.'},
            {'day': 3, 'title': 'Mekong Delta', 'desc': 'Boat tour, floating market, homestay.'},
            {'day': 4, 'title': 'Fly to Da Nang', 'desc': 'My Khe Beach, Marble Mountain.'},
            {'day': 5, 'title': 'Hoi An', 'desc': 'Ancient town, tailor shops, mooncake factory.'},
            {'day': 6, 'title': 'Ha Long Bay', 'desc': 'Overnight cruise, kayak, cave exploration.'},
            {'day': 7, 'title': 'Hanoi', 'desc': 'Old Quarter, Ho Chi Minh Mausoleum.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last pho, fly home.'},
        ],
    },
    'mu': {
        'best_time': 'May to December',
        'currency': 'MUR', 'language': 'English / French / Creole',
        'weather': 'Subtropical; Winter 22–26°C',
        'attractions': [
            {'id': 'a1', 'name': 'Le Morne Beach', 'city': 'Le Morne'},
            {'id': 'a2', 'name': 'Port Louis Market', 'city': 'Port Louis'},
            {'id': 'a3', 'name': 'Chamarel Seven Colored Earth', 'city': 'Chamarel'},
            {'id': 'a4', 'name': 'Ile aux Cerfs', 'city': 'Trou d\'Eau Douce'},
            {'id': 'a5', 'name': 'Casela Nature Park', 'city': 'Riviere Noire'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Mauritius', 'desc': 'Check-in, Le Morne beach sunset.'},
            {'day': 2, 'title': 'Ile aux Cerfs', 'desc': 'Catamaran, snorkeling, BBQ on island.'},
            {'day': 3, 'title': 'Southwest', 'desc': 'Chamarel falls, seven colors earth, rum distillery.'},
            {'day': 4, 'title': 'Port Louis', 'desc': 'Central Market, Caudan,Fortifications.'},
            {'day': 5, 'title': 'Casela Park', 'desc': 'Zipline, walk with lions,viewpoint.'},
            {'day': 6, 'title': 'Free day', 'desc': 'Spa, golf, or optional excursion.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last swim, airport transfer.'},
        ],
    },
    'sc': {
        'best_time': 'April to May, October to November',
        'currency': 'SCR', 'language': 'English / French / Creole',
        'weather': 'Tropical; 24–30°C year-round',
        'attractions': [
            {'id': 'a1', 'name': 'Anse Lazio Beach', 'city': 'Praslin'},
            {'id': 'a2', 'name': 'Vallee de Mai', 'city': 'Praslin'},
            {'id': 'a3', 'name': 'La Digue Island', 'city': 'La Digue'},
            {'id': 'a4', 'name': 'Victoria Market', 'city': 'Mahe'},
            {'id': 'a5', 'name': 'Beau Vallon', 'city': 'Mahe'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Mahe', 'desc': 'Beau Vallon beach, sunset market.'},
            {'day': 2, 'title': 'Victoria', 'desc': 'Botanical gardens, Sir Selabi Secheles.'},
            {'day': 3, 'title': 'Sainte Anne', 'desc': 'Marine park, snorkeling.'},
            {'day': 4, 'title': 'Praslin', 'desc': 'Vallee de Mai, Anse Lazio.'},
            {'day': 5, 'title': 'La Digue', 'desc': 'Bike around, Anse Source d\'Argent.'},
            {'day': 6, 'title': 'Depart', 'desc': 'Last beach, fly home.'},
        ],
    },
    'nz': {
        'best_time': 'December to March (summer) or June to August (skiing)',
        'currency': 'NZD', 'language': 'English / Maori',
        'weather': 'Temperate; Summer 16–24°C, Winter 8–16°C',
        'attractions': [
            {'id': 'a1', 'name': 'Milford Sound', 'city': 'Fiordland'},
            {'id': 'a2', 'name': 'Sky Tower', 'city': 'Auckland'},
            {'id': 'a3', 'name': 'Rotorua Geothermal', 'city': 'Rotorua'},
            {'id': 'a4', 'name': 'Hobbiton', 'city': 'Matamata'},
            {'id': 'a5', 'name': 'Queenstown', 'city': 'Otago'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Auckland', 'desc': 'Sky Tower, Viaduct Harbour,尝地道海鲜.'},
            {'day': 2, 'title': 'Waitomo Caves', 'desc': 'Glowworm cave, blackwater rafting.'},
            {'day': 3, 'title': 'Rotorua', 'desc': 'Geothermal parks, Maori cultural experience, Haka.'},
            {'day': 4, 'title': 'Hobbiton + Farm', 'desc': 'Lord of the Rings set, sheep station.'},
            {'day': 5, 'title': 'Fly to Queenstown', 'desc': 'Lake Wakatipu, Ferg Burger.'},
            {'day': 6, 'title': 'Milford Sound', 'desc': 'Scenic drive, fiord cruise.'},
            {'day': 7, 'title': 'Adventure day', 'desc': 'Bungee, jet boat, or ski (seasonal).'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last hikes, fly home.'},
        ],
    },
    'tr': {
        'best_time': 'April to June, September to November',
        'currency': 'TRY', 'language': 'Turkish',
        'weather': 'Mediterranean; Spring 15–25°C',
        'attractions': [
            {'id': 'a1', 'name': 'Hagia Sophia', 'city': 'Istanbul'},
            {'id': 'a2', 'name': 'Cappadocia', 'city': 'Nevsehir'},
            {'id': 'a3', 'name': 'Ephesus', 'city': 'Izmir'},
            {'id': 'a4', 'name': 'Pamukkale', 'city': 'Denizli'},
            {'id': 'a5', 'name': 'Blue Mosque', 'city': 'Istanbul'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Istanbul', 'desc': 'Sultanahmet, Blue Mosque, Grand Bazaar.'},
            {'day': 2, 'title': 'Hagia Sophia + Topkapi', 'desc': 'Historic heart, Cistern Basilica.'},
            {'day': 3, 'title': 'Bosphorus cruise', 'desc': 'Spice Market, ferry to Asia side.'},
            {'day': 4, 'title': 'Fly to Cappadocia', 'desc': 'Hot air balloon at sunrise, cave hotel.'},
            {'day': 5, 'title': 'Cappadocia tour', 'desc': 'Underground city, valley hike, pottery.'},
            {'day': 6, 'title': 'Ephesus day trip', 'desc': 'Ancient Roman city, Library of Celsus.'},
            {'day': 7, 'title': 'Pamukkale', 'desc': 'White travertines, Hierapolis ruins.'},
            {'day': 8, 'title': 'Return Istanbul', 'desc': 'Galata Tower, taksim Square.'},
            {'day': 9, 'title': 'Depart', 'desc': 'Last shopping, fly home.'},
        ],
    },
    'eg': {
        'best_time': 'October to April',
        'currency': 'EGP', 'language': 'Arabic',
        'weather': 'Desert; Winter 14–24°C',
        'attractions': [
            {'id': 'a1', 'name': 'Pyramids of Giza', 'city': 'Giza'},
            {'id': 'a2', 'name': 'Luxor Temple', 'city': 'Luxor'},
            {'id': 'a3', 'name': 'Valley of the Kings', 'city': 'Luxor'},
            {'id': 'a4', 'name': 'Egyptian Museum', 'city': 'Cairo'},
            {'id': 'a5', 'name': 'Nile Cruise', 'city': 'Aswan'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Cairo', 'desc': 'Pyramids at sunset, Sound & Light show.'},
            {'day': 2, 'title': 'Pyramids + Museum', 'desc': 'Giza pyramids, Sphinx, Egyptian Museum.'},
            {'day': 3, 'title': 'Fly to Luxor', 'desc': 'Valley of the Kings, Hatshepsut Temple.'},
            {'day': 4, 'title': 'Luxor temples', 'desc': 'Karnak, Luxor Temple, hot air balloon.'},
            {'day': 5, 'title': 'Nile cruise start', 'desc': 'Board cruise, Edfu Temple.'},
            {'day': 6, 'title': 'Aswan', 'desc': 'Philae Temple, High Dam, Felucca ride.'},
            {'day': 7, 'title': 'Abu Simbel', 'desc': 'Day trip to the great temples.'},
            {'day': 8, 'title': 'Return Cairo', 'desc': 'Khan el-Bakili market, fly home.'},
        ],
    },
    'ke': {
        'best_time': 'July to October, January to February',
        'currency': 'KES', 'language': 'English / Swahili',
        'weather': 'Tropical; Summer 20–30°C',
        'attractions': [
            {'id': 'a1', 'name': 'Maasai Mara', 'city': 'Narok'},
            {'id': 'a2', 'name': 'Nairobi National Park', 'city': 'Nairobi'},
            {'id': 'a3', 'name': 'Amboseli', 'city': 'Kajiado'},
            {'id': 'a4', 'name': 'Diani Beach', 'city': 'Mombasa'},
            {'id': 'a5', 'name': 'Lamu Old Town', 'city': 'Lamu'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Nairobi', 'desc': 'Kenyatta International, Giraffe Centre.'},
            {'day': 2, 'title': 'Nairobi city tour', 'desc': 'Karen Blixen Museum, Uhuru Gardens.'},
            {'day': 3, 'title': 'Fly to Maasai Mara', 'desc': 'Game drive, Big Five safari.'},
            {'day': 4, 'title': 'Mara full day', 'desc': 'Morning & afternoon game drives, balloon safari.'},
            {'day': 5, 'title': 'Mara to Amboseli', 'desc': 'Drive to Amboseli, Mt Kilimanjaro views.'},
            {'day': 6, 'title': 'Amboseli safari', 'desc': 'Elephant herds, sunset over Kilimanjaro.'},
            {'day': 7, 'title': 'Fly to Diani', 'desc': 'White sand beach, snorkel.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last beach day, fly home.'},
        ],
    },
    'fj': {
        'best_time': 'May to October',
        'currency': 'FJD', 'language': 'English / Fijian / Hindi',
        'weather': 'Tropical; Winter 22–28°C',
        'attractions': [
            {'id': 'a1', 'name': 'Manta Ray Island', 'city': 'Yanuca'},
            {'id': 'a2', 'name': 'Sigatoka Sand Dunes', 'city': 'Sigatoka'},
            {'id': 'a3', 'name': 'Garden of the Sleeping Giant', 'city': 'Nadi'},
            {'id': 'a4', 'name': 'Cloudbreak Surf', 'city': 'Malolo Lailai'},
            {'id': 'a5', 'name': 'Suva City', 'city': 'Suva'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Nadi', 'desc': 'Garden of the Giants, Denarau Marina.'},
            {'day': 2, 'title': 'Island hopping', 'desc': 'South Sea Island, snorkeling.'},
            {'day': 3, 'title': 'Sigatoka Sand Dunes', 'desc': 'Off-road adventure, Kula Eco Park.'},
            {'day': 4, 'title': 'Manta Ray day', 'desc': 'Snorkel with mantas, Beachouse stay.'},
            {'day': 5, 'title': 'Cloudbreak surf', 'desc': 'Surf lesson or spectator at the famous break.'},
            {'day': 6, 'title': 'Relaxation', 'desc': 'Beach day, spa, fijian medicine ceremony.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last swim, duty-free shopping.'},
        ],
    },
    'om': {
        'best_time': 'October to March',
        'currency': 'OMR', 'language': 'Arabic / English',
        'weather': 'Desert; Winter 18–28°C',
        'attractions': [
            {'id': 'a1', 'name': 'Sultan Qaboos Grand Mosque', 'city': 'Muscat'},
            {'id': 'a2', 'name': 'Wadi Shab', 'city': 'Ash-Sharqiyah'},
            {'id': 'a3', 'name': 'Nizwa Fort', 'city': 'Nizwa'},
            {'id': 'a4', 'name': 'Wadi Bani Khalid', 'city': 'Ash-Sharqiyah'},
            {'id': 'a5', 'name': 'The Mutrah Souq', 'city': 'Muscat'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Muscat', 'desc': 'Grand Mosque, Mutrah Corniche.'},
            {'day': 2, 'title': 'Old Muscat', 'desc': 'Sultans Palace, Al Jalali Forts.'},
            {'day': 3, 'title': 'Nizwa day', 'desc': 'Nizwa Fort, goat market, falaj irrigation.'},
            {'day': 4, 'title': 'Mountain wadi', 'desc': 'Wadi Shab hike, natural pools.'},
            {'day': 5, 'title': 'Desert experience', 'desc': 'Wahiba Sands overnight camp.'},
            {'day': 6, 'title': 'Return Muscat', 'desc': 'Opera House, Royal Opera House.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last shopping at souq, fly home.'},
        ],
    },
    'sa': {
        'best_time': 'November to February',
        'currency': 'SAR', 'language': 'Arabic',
        'weather': 'Desert; Winter 15–25°C',
        'attractions': [
            {'id': 'a1', 'name': 'Kingdom Centre Tower', 'city': 'Riyadh'},
            {'id': 'a2', 'name': 'Al Masmak Fortress', 'city': 'Riyadh'},
            {'id': 'a3', 'name': 'Jeddah Corniche', 'city': 'Jeddah'},
            {'id': 'a4', 'name': 'Madainn Saleh', 'city': 'AlUla'},
            {'id': 'a5', 'name': 'Taif Rose Farm', 'city': 'Taif'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Riyadh', 'desc': 'Kingdom Centre Sky Bridge, Boulevard.'},
            {'day': 2, 'title': 'Riyadh historic', 'desc': 'Al Masmak, National Museum, Deera Square.'},
            {'day': 3, 'title': 'Fly to Jeddah', 'desc': 'Al-Balad old town, floating mosque.'},
            {'day': 4, 'title': 'Jeddah corniche', 'desc': 'Corniche walk, King Fahd Fountain.'},
            {'day': 5, 'title': 'AlUla day trip', 'desc': 'Madainn Saleh, Hegra experience.'},
            {'day': 6, 'title': 'Taif', 'desc': 'Rose farms, Shafa mountain, coffee.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last shopping, fly home.'},
        ],
    },
    'ru': {
        'best_time': 'June to August (summer) or December to February (skiing)',
        'currency': 'RUB', 'language': 'Russian',
        'weather': 'Continental; Summer 15–28°C, Winter -10 to -20°C',
        'attractions': [
            {'id': 'a1', 'name': 'Red Square', 'city': 'Moscow'},
            {'id': 'a2', 'name': 'Hermitage Museum', 'city': 'St Petersburg'},
            {'id': 'a3', 'name': 'St Basil\'s Cathedral', 'city': 'Moscow'},
            {'id': 'a4', 'name': 'Peterhof Palace', 'city': 'St Petersburg'},
            {'id': 'a5', 'name': 'Kremlin', 'city': 'Moscow'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Moscow', 'desc': 'Red Square at night, Kremlin walls.'},
            {'day': 2, 'title': 'Moscow highlights', 'desc': 'St Basil\'s, GUM shopping, Moscow metro.'},
            {'day': 3, 'title': 'Moscow museums', 'desc': 'Tretyakov Gallery, Cosmonaut Museum.'},
            {'day': 4, 'title': 'Sapsan to St Petersburg', 'desc': 'High-speed train, check in.'},
            {'day': 5, 'title': 'Hermitage day', 'desc': 'Winter Palace, Gold Eagle exhibit.'},
            {'day': 6, 'title': 'Peterhof', 'desc': 'Fountain spectacle, Peterhof gardens.'},
            {'day': 7, 'title': 'Peterburg return', 'desc': 'Church of Savior, Nevsky Prospect.'},
            {'day': 8, 'title': 'Return Moscow', 'desc': 'Last逛, fly home.'},
        ],
    },
    'bh': {
        'best_time': 'November to March',
        'currency': 'BHD', 'language': 'Arabic / English',
        'weather': 'Desert; Winter 15–26°C',
        'attractions': [
            {'id': 'a1', 'name': 'Bahrain Fort', 'city': 'Manama'},
            {'id': 'a2', 'name': 'Tree of Life', 'city': 'Desert'},
            {'id': 'a3', 'name': 'Bab el Bahrain Souq', 'city': 'Manama'},
            {'id': 'a4', 'name': 'Al Fateh Grand Mosque', 'city': 'Manama'},
            {'id': 'a5', 'name': 'Qal\' al Bahrain', 'city': 'Muharraq'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Manama', 'desc': 'Corniche walk, Bahrain Bay.'},
            {'day': 2, 'title': 'Historic tour', 'desc': 'Bahrain Fort, Qal\'al Muharraq.'},
            {'day': 3, 'title': 'Museums & Mosques', 'desc': 'National Museum, Al Fateh Mosque.'},
            {'day': 4, 'title': 'Desert adventure', 'desc': 'Tree of Life, oil museum, 4x4 dunes.'},
            {'day': 5, 'title': 'Island relaxation', 'desc': 'Beaches, water sports, dive site.'},
            {'day': 6, 'title': 'Shopping', 'desc': 'City Centre Mall, Gold Souq.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last falafel, fly home.'},
        ],
    },
    'kw': {
        'best_time': 'October to April',
        'currency': 'KWD', 'language': 'Arabic / English',
        'weather': 'Desert; Winter 12–25°C',
        'attractions': [
            {'id': 'a1', 'name': 'Kuwait Towers', 'city': 'Kuwait City'},
            {'id': 'a2', 'name': 'The Grand Mosque', 'city': 'Kuwait City'},
            {'id': 'a3', 'name': 'Failaka Island', 'city': 'Kuwait'},
            {'id': 'a4', 'name': 'Souq al-Manakh', 'city': 'Kuwait City'},
            {'id': 'a5', 'name': 'Jaber Al Ahmed', 'city': 'Kuwait City'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Kuwait City', 'desc': 'Kuwait Towers, Marina promenade.'},
            {'day': 2, 'title': 'City tour', 'desc': 'Grand Mosque, Liberation Tower.'},
            {'day': 3, 'title': 'Cultural district', 'desc': 'National Museum, Sadu House.'},
            {'day': 4, 'title': 'Failaka Island', 'desc': 'Greek ruins, beach day.'},
            {'day': 5, 'title': 'Desert safari', 'desc': 'Dune bashing, Bedouin camp.'},
            {'day': 6, 'title': 'Last day', 'desc': 'Shopping at Mall, fly home.'},
        ],
    },
    'tz': {
        'best_time': 'June to October, December to February',
        'currency': 'TZS', 'language': 'Swahili / English',
        'weather': 'Tropical; Summer 20–30°C',
        'attractions': [
            {'id': 'a1', 'name': 'Serengeti National Park', 'city': 'Serengeti'},
            {'id': 'a2', 'name': 'Mount Kilimanjaro', 'city': 'Moshi'},
            {'id': 'a3', 'name': 'Ngorongoro Crater', 'city': 'Arusha'},
            {'id': 'a4', 'name': 'Zanzibar Beach', 'city': 'Zanzibar'},
            {'id': 'a5', 'name': 'Stone Town', 'city': 'Zanzibar'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Kilimanjaro', 'desc': 'Moshi town, Chagga coffee tour.'},
            {'day': 2, 'title': 'Arusha', 'desc': 'Coffee tour, Cultural Heritage Centre.'},
            {'day': 3, 'title': 'Ngorongoro', 'desc': 'Crater floor safari, crater view.'},
            {'day': 4, 'title': 'Serengeti', 'desc': 'Big Five safari, Great Migration (seasonal).'},
            {'day': 5, 'title': 'Serengeti full day', 'desc': 'Morning game drive, hot air balloon.'},
            {'day': 6, 'title': 'Fly to Zanzibar', 'desc': 'Stone Town, sunset dhow cruise.'},
            {'day': 7, 'title': 'Beach day', 'desc': 'Nungwi beach, snorkeling.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last spice tour, fly home.'},
        ],
    },
    'ug': {
        'best_time': 'June to September, December to February',
        'currency': 'UGX', 'language': 'English / Swahili',
        'weather': 'Tropical; Summer 18–28°C',
        'attractions': [
            {'id': 'a1', 'name': 'Mountain Gorillas', 'city': 'Bwindi'},
            {'id': 'a2', 'name': 'Murchison Falls', 'city': 'Masindi'},
            {'id': 'a3', 'name': 'Queen Elizabeth NP', 'city': 'Kasese'},
            {'id': 'a4', 'name': 'Lake Bunyonyi', 'city': 'Kisoro'},
            {'id': 'a5', 'name': 'Kampala', 'city': 'Kampala'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Entebbe', 'desc': 'Botanical gardens, lake sunset.'},
            {'day': 2, 'title': 'Drive to Bwindi', 'desc': 'Scenic drive, tea plantations.'},
            {'day': 3, 'title': 'Gorilla trekking', 'desc': 'Life-changing mountain gorilla encounter.'},
            {'day': 4, 'title': 'Lake Bunyonyi', 'desc': 'Relaxation, canoe, terraced hills.'},
            {'day': 5, 'title': 'Queen Elizabeth NP', 'desc': 'Boat safari on Kazinga Channel.'},
            {'day': 6, 'title': 'Game drive', 'desc': 'Tree-climbing lions, big five.'},
            {'day': 7, 'title': 'Return Kampala', 'desc': 'Craft markets, farewell dinner.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last shopping, fly home.'},
        ],
    },
    'zw': {
        'best_time': 'May to October (dry season)',
        'currency': 'ZWL', 'language': 'English / Shona / Ndebele',
        'weather': 'Subtropical; Winter 15–28°C',
        'attractions': [
            {'id': 'a1', 'name': 'Victoria Falls', 'city': 'Victoria Falls'},
            {'id': 'a2', 'name': 'Hwange National Park', 'city': 'Hwange'},
            {'id': 'a3', 'name': 'Great Zimbabwe', 'city': 'Masvingo'},
            {'id': 'a4', 'name': 'Lake Kariba', 'city': 'Kariba'},
            {'id': 'a5', 'name': 'Chimanimani', 'city': 'Chimanimani'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Victoria Falls', 'desc': 'Falls viewpoint, Devil\'s Pool (seasonal).'},
            {'day': 2, 'title': 'Adventure day', 'desc': 'Bungee, white water rafting, helicopter.'},
            {'day': 3, 'title': 'Hwange safari', 'desc': 'Game drive, waterhole watching.'},
            {'day': 4, 'title': 'Sunset cruise', 'desc': 'Zambezi sunset cruise, hippos.'},
            {'day': 5, 'title': 'Flight to Great Zimbabwe', 'desc': 'Ancient ruins, Great Zimbabwe.'},
            {'day': 6, 'title': 'Lake Kariba', 'desc': 'Houseboat, fishing, crocodiles.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last view of falls, fly home.'},
        ],
    },
    'mm': {
        'best_time': 'November to February',
        'currency': 'MMK', 'language': 'Burmese',
        'weather': 'Tropical; Winter 20–30°C',
        'attractions': [
            {'id': 'a1', 'name': 'Shwedagon Pagoda', 'city': 'Yangon'},
            {'id': 'a2', 'name': 'Bagan Temples', 'city': 'Bagan'},
            {'id': 'a3', 'name': 'Inle Lake', 'city': 'Nyaungshwe'},
            {'id': 'a4', 'name': 'Mandalay Hill', 'city': 'Mandalay'},
            {'id': 'a5', 'name': 'U Bein Bridge', 'city': 'Amarapura'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Yangon', 'desc': 'Shwedagon Pagoda at sunset.'},
            {'day': 2, 'title': 'Yangon colonial', 'desc': 'Scott Market, Sule Pagoda.'},
            {'day': 3, 'title': 'Fly to Bagan', 'desc': 'Temple sunrise, bicycle around.'},
            {'day': 4, 'title': 'Bagan temples', 'desc': 'Hot air balloon (seasonal), archaeological museum.'},
            {'day': 5, 'title': 'Fly to Inle Lake', 'desc': 'Floating gardens, leg rowing fishermen.'},
            {'day': 6, 'title': 'Inle full day', 'desc': 'Market day, Indein pagoda, tribal villages.', },
            {'day': 7, 'title': 'Mandalay', 'desc': 'U Bein Bridge sunset, Mahagiri Monastery.'},
            {'day': 8, 'title': 'Depart', 'desc': 'Last temple visit, fly home.'},
        ],
    },
    'la': {
        'best_time': 'November to March',
        'currency': 'LAK', 'language': 'Lao',
        'weather': 'Tropical; Winter 15–28°C',
        'attractions': [
            {'id': 'a1', 'name': 'Kuang Si Falls', 'city': 'Luang Prabang'},
            {'id': 'a2', 'name': 'Wat Phou', 'city': 'Champasak'},
            {'id': 'a3', 'name': 'Patuxay Monument', 'city': 'Vientiane'},
            {'id': 'a4', 'name': '4000 Islands', 'city': 'Si Phan Don'},
            {'id': 'a5', 'name': 'Luang Prabang Old Town', 'city': 'Luang Prabang'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Luang Prabang', 'desc': 'Mount Phousi, night market.'},
            {'day': 2, 'title': 'Waterfalls day', 'desc': 'Kuang Si Falls, bear rescue, swim.'},
            {'day': 3, 'title': 'Temples tour', 'desc': 'Royal Palace, Wat Xieng Thong.'},
            {'day': 4, 'title': ' Mekong cruise', 'desc': 'Slow boat to 4000 Islands.'},
            {'day': 5, 'title': '4000 Islands', 'desc': 'Khone Phapeng waterfalls, irrawaddy dolphins.'},
            {'day': 6, 'title': 'Fly to Vientiane', 'desc': 'Patuxay, That Luang, COPE.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last Lao coffee, fly home.'},
        ],
    },
    'kh': {
        'best_time': 'November to March',
        'currency': 'KHR', 'language': 'Khmer',
        'weather': 'Tropical; Winter 20–32°C',
        'attractions': [
            {'id': 'a1', 'name': 'Angkor Wat', 'city': 'Siem Reap'},
            {'id': 'a2', 'name': 'Angkor Thom', 'city': 'Siem Reap'},
            {'id': 'a3', 'name': 'Tonle Sap', 'city': 'Siem Reap'},
            {'id': 'a4', 'name': 'Phnom Penh', 'city': 'Phnom Penh'},
            {'id': 'a5', 'name': 'Sihanoukville', 'city': 'Sihanoukville'},
        ],
        'itinerary': [
            {'day': 1, 'title': 'Arrive Siem Reap', 'desc': 'Angkor National Museum, Pub Street.'},
            {'day': 2, 'title': 'Angkor sunrise', 'desc': 'Sunrise at Angkor Wat, Bayon temple.'},
            {'day': 3, 'title': 'Ta Prohm + Banteay', 'desc': 'Tomb Raider temple, Banteay Srei.'},
            {'day': 4, 'title': 'Tonle Sap', 'desc': 'Floating village, Tonle Sap Lake.'},
            {'day': 5, 'title': 'Fly to Phnom Penh', 'desc': 'Royal Palace, Killing Fields.'},
            {'day': 6, 'title': 'Sihanoukville', 'desc': 'Beach time, Otres Beach.'},
            {'day': 7, 'title': 'Depart', 'desc': 'Last fried spider snack, fly home.'},
        ],
    },
}


def get_country(country_id: str):
    return next((c for c in COUNTRIES if c['id'] == country_id), None)


def get_holiday_plan(country_id: str, country_meta: dict = None):
    plan = HOLIDAY_PLANS.get(country_id)
    if plan:
        return plan

    region = (country_meta or {}).get('region', '')
    capital = (country_meta or {}).get('capital', '')
    currencies = (country_meta or {}).get('currencies', [])
    languages = (country_meta or {}).get('languages', [])
    subregion = (country_meta or {}).get('subregion', '')

    currency = currencies[0] if currencies else '—'
    language = '/'.join(languages[:2]) if languages else '—'

    best_time_map = {
        'Africa': 'November to March',
        'Americas': 'December to April',
        'Asia': 'October to March',
        'Europe': 'April to June, September to October',
        'Oceania': 'September to November',
    }
    best_time = best_time_map.get(region, 'Year round')

    weather_map = {
        'Africa': 'Tropical; Winter 20–32°C',
        'Americas': 'Temperate; varies by location',
        'Asia': 'Tropical to subtropical; varies',
        'Europe': 'Temperate; Spring 10–22°C',
        'Oceania': 'Subtropical; Spring 16–26°C',
    }
    weather = weather_map.get(region, 'Pleasant most of the year')

    capital_name = capital if capital else 'the capital city'

    attractions = [
        {'id': 'g1', 'name': f'Historic {capital_name}', 'city': capital_name},
        {'id': 'g2', 'name': 'National Museum', 'city': capital_name},
        {'id': 'g3', 'name': 'Central Market', 'city': capital_name},
        {'id': 'g4', 'name': f'Regional {region} Heritage Site', 'city': 'Regional'},
        {'id': 'g5', 'name': 'Nature Reserve / Park', 'city': 'Outskirts'},
    ]

    itinerary_templates = {
        'Africa': [
            {'day': 1, 'title': f'Arrive {capital_name}', 'desc': 'Check-in, local market visit.'},
            {'day': 2, 'title': 'City tour', 'desc': 'Historic center, colonial architecture.'},
            {'day': 3, 'title': 'National museum', 'desc': 'Cultural heritage, tribal history.'},
            {'day': 4, 'title': 'Day trip', 'desc': 'Wildlife reserve or scenic nature walk.'},
            {'day': 5, 'title': 'Beach / Lake', 'desc': 'Relax at waterfront, water sports.'},
            {'day': 6, 'title': 'Local experiences', 'desc': 'Cooking class, craft workshop.'},
            {'day': 7, 'title': 'Departure', 'desc': 'Souvenir shopping, airport transfer.'},
        ],
        'Asia': [
            {'day': 1, 'title': f'Arrive {capital_name}', 'desc': 'Temple visit, street food.'},
            {'day': 2, 'title': 'Historic old town', 'desc': 'Palace or fortress, heritage walk.'},
            {'day': 3, 'title': 'Markets & bazaar', 'desc': 'Local shopping, bargaining.'},
            {'day': 4, 'title': 'Nature day', 'desc': 'Gardens, hilltop viewpoints.'},
            {'day': 5, 'title': 'Cultural show', 'desc': 'Traditional dance or performance.'},
            {'day': 6, 'title': 'Day trip', 'desc': 'Nearby island, mountain, or village.'},
            {'day': 7, 'title': 'Last day', 'desc': 'Spa, last shopping, fly home.'},
        ],
        'Europe': [
            {'day': 1, 'title': f'Arrive {capital_name}', 'desc': 'Old town walk, cathedral.'},
            {'day': 2, 'title': 'Museums', 'desc': 'National gallery, history museum.'},
            {'day': 3, 'title': 'Palace / Castle', 'desc': 'Royal residence, gardens.'},
            {'day': 4, 'title': 'Walking tour', 'desc': 'Historic squares, bridges.'},
            {'day': 5, 'title': 'Day trip', 'desc': 'Nearby town or scenic countryside.'},
            {'day': 6, 'title': 'Local cuisine', 'desc': 'Food tour, wine tasting.'},
            {'day': 7, 'title': 'Departure', 'desc': 'Last stroll, fly home.'},
        ],
        'Americas': [
            {'day': 1, 'title': f'Arrive {capital_name}', 'desc': 'Downtown walk, welcome dinner.'},
            {'day': 2, 'title': 'Historic district', 'desc': 'Colonial architecture, plaza.'},
            {'day': 3, 'title': 'Museum day', 'desc': 'Art museum, natural history.'},
            {'day': 4, 'title': 'Nature', 'desc': 'Botanical garden or city park.'},
            {'day': 5, 'title': 'Day trip', 'desc': 'Beach, volcano, or scenic drive.'},
            {'day': 6, 'title': 'Local culture', 'desc': 'Market visit, artisan workshops.'},
            {'day': 7, 'title': 'Departure', 'desc': 'Last souvenirs, fly home.'},
        ],
        'Oceania': [
            {'day': 1, 'title': f'Arrive {capital_name}', 'desc': 'Harbor walk, beach arrival.'},
            {'day': 2, 'title': 'City tour', 'desc': 'Cultural center, waterfront.'},
            {'day': 3, 'title': 'Wildlife', 'desc': 'Zoo, aquarium, or sanctuary.'},
            {'day': 4, 'title': 'Beach day', 'desc': 'Snorkeling, surfing, or diving.'},
            {'day': 5, 'title': 'Island hop', 'desc': 'Ferry to nearby island.'},
            {'day': 6, 'title': 'Nature walk', 'desc': 'National park, viewpoints.'},
            {'day': 7, 'title': 'Departure', 'desc': 'Last swim, fly home.'},
        ],
    }

    itinerary = itinerary_templates.get(region, [
        {'day': 1, 'title': f'Arrive {capital_name}', 'desc': 'Check into hotel, explore local area.'},
        {'day': 2, 'title': 'Historic center', 'desc': 'Old town, main square, cathedral.'},
        {'day': 3, 'title': 'Museums', 'desc': 'National museum, art gallery.'},
        {'day': 4, 'title': 'Parks & Gardens', 'desc': 'Botanical garden, city park.'},
        {'day': 5, 'title': 'Local experiences', 'desc': 'Market visit, cooking class.'},
        {'day': 6, 'title': 'Day trip', 'desc': 'Nearby village or scenic spot.'},
        {'day': 7, 'title': 'Last day', 'desc': 'Souvenir shopping, fly home.'},
    ])

    return {
        'best_time': best_time,
        'currency': currency,
        'language': language,
        'weather': weather,
        'attractions': attractions,
        'itinerary': itinerary,
    }
