"""Third-party service integrations registry.

Categories:
- visa_apis:   Atlys, VisaHQ, iVisa  (real-time visa requirements)
- travel_booking: Skyscanner, Amadeus, Booking.com  (flights / hotels)
- payments_forex: Razorpay, Wise API, Stripe  (payments + FX rates)
- travel_insurance: Travelex, Go Digit, Policy Bazaar  (insurance quotes)
- appt_slots:  VFS Global, BLS Intl  (appointment slot monitoring)
"""

from __future__ import annotations

SERVICE_CATEGORIES = [
    {
        "id": "visa_apis",
        "name": "Visa APIs",
        "description": "Real-time visa requirements, document checklists, and application status",
        "services": [
            {
                "id": "atlys",
                "name": "Atlys",
                "description": "Visa requirements by country pair — rules, documents, fees, timelines",
                "website": "https://atlys.com",
                "docs": "https://docs.atlys.com",
                "category": "visa_apis",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "atlys_...",
                "base_url": "https://api.atlys.com/v1",
                "features": ["visa_requirements", "document_checklist", "country_rules", "fee_schedule"],
                "powered_by_tagline": "Powered by Atlys in Association with We Hive",
            },
            {
                "id": "visahq",
                "name": "VisaHQ",
                "description": "Visa application support and requirements for 200+ countries",
                "website": "https://visahq.com",
                "docs": "https://visahq.com/api/docs",
                "category": "visa_apis",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "vq_...",
                "base_url": "https://api.visahq.com/v1",
                "features": ["visa_requirements", "application_form", "status_tracking"],
                "powered_by_tagline": "Powered by VisaHQ in Association with We Hive",
            },
            {
                "id": "ivisa",
                "name": "iVisa",
                "description": "Fast-track visa applications and real-time status tracking",
                "website": "https://ivisa.com",
                "docs": "https://ivisa.com/developers",
                "category": "visa_apis",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "iv_...",
                "base_url": "https://api.ivisa.com/v1",
                "features": ["visa_application", "status_tracking", "document_review"],
                "powered_by_tagline": "Powered by iVisa in Association with We Hive",
            },
        ],
    },
    {
        "id": "travel_booking",
        "name": "Travel Booking",
        "description": "Flight and hotel search, pricing, and booking — convert planning into bookings",
        "services": [
            {
                "id": "skyscanner",
                "name": "Skyscanner",
                "description": "Flight and hotel search API with live pricing from 1,200+ travel sites",
                "website": "https://skyscanner.com",
                "docs": "https://developers.skyscanner.net",
                "category": "travel_booking",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "skyscanner_...",
                "base_url": "https://skyscanner-provider-api.com/v1",
                "features": ["flight_search", "hotel_search", "price_comparison", "booking_link"],
                "powered_by_tagline": "Powered by Skyscanner in Association with We Hive",
            },
            {
                "id": "amadeus",
                "name": "Amadeus",
                "description": "Professional travel APIs — flight search, booking, NDC, schedule and hotel",
                "website": "https://amadeus.com",
                "docs": "https://developers.amadeus.com",
                "category": "travel_booking",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "amadeus_...",
                "base_url": "https://test.api.amadeus.com/v2",
                "features": ["flight_search", "flight_booking", "hotel_search", "seat_maps", "tourist_insights"],
                "powered_by_tagline": "Powered by Amadeus in Association with We Hive",
            },
            {
                "id": "bookingcom",
                "name": "Booking.com",
                "description": "Hotel inventory, availability and booking integration",
                "website": "https://booking.com",
                "docs": "https://www.booking.com/developer/apiphp.html",
                "category": "travel_booking",
                "requires_key": True,
                "key_label": "Affiliate PID",
                "key_placeholder": "booking_...",
                "base_url": "https://supply-xml.booking.com/hotels-api",
                "features": ["hotel_search", "availability", "booking", "review_stars"],
                "powered_by_tagline": "Powered by Booking.com in Association with We Hive",
            },
        ],
    },
    {
        "id": "payments_forex",
        "name": "Payments and Forex",
        "description": "Accept visa fee payments and live currency exchange rates for budgeting",
        "services": [
            {
                "id": "razorpay",
                "name": "Razorpay",
                "description": "Accept visa fee payments — cards, UPI, net banking, wallets",
                "website": "https://razorpay.com",
                "docs": "https://razorpay.com/docs/",
                "category": "payments_forex",
                "requires_key": True,
                "key_label": "Key ID",
                "key_placeholder": "rzp_...",
                "base_url": "https://api.razorpay.com/v1",
                "features": ["payment_gateway", "upi", "cards", "wallets", "webhook"],
                "powered_by_tagline": "Powered by Razorpay in Association with We Hive",
            },
            {
                "id": "wise",
                "name": "Wise API",
                "description": "Live mid-market exchange rates and international transfers",
                "website": "https://wise.com",
                "docs": "https://wise.com/docs",
                "category": "payments_forex",
                "requires_key": True,
                "key_label": "API Token",
                "key_placeholder": "wise_...",
                "base_url": "https://api.wise.com/v1",
                "features": ["exchange_rates", "currency_conversion", "transfer_tracking"],
                "powered_by_tagline": "Powered by Wise in Association with We Hive",
            },
            {
                "id": "stripe",
                "name": "Stripe",
                "description": "Global payment processing — cards, Apple Pay, Google Pay, SEPA",
                "website": "https://stripe.com",
                "docs": "https://stripe.com/docs/developers",
                "category": "payments_forex",
                "requires_key": True,
                "key_label": "Secret Key",
                "key_placeholder": "sk_...",
                "base_url": "https://api.stripe.com/v1",
                "features": ["payment_gateway", "invoicing", "subscriptions", "fx_conversion"],
                "powered_by_tagline": "Powered by Stripe in Association with We Hive",
            },
        ],
    },
    {
        "id": "travel_insurance",
        "name": "Travel Insurance",
        "description": "Embed insurance quotes and purchase flows — required for Schengen and UK visas",
        "services": [
            {
                "id": "travelex",
                "name": "Travelex",
                "description": "International travel insurance policies with instant online purchase",
                "website": "https://travelex.com",
                "docs": "https://api.travelex.com/docs",
                "category": "travel_insurance",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "travelex_...",
                "base_url": "https://api.travelex.com/v1",
                "features": ["get_quote", "policy_purchase", "claim_status", "coverage_details"],
                "powered_by_tagline": "Powered by Travelex in Association with We Hive",
            },
            {
                "id": "godigit",
                "name": "Go Digit",
                "description": "Digital-first travel insurance — comprehensive, affordable, fast claims",
                "website": "https://godigit.com",
                "docs": "https://api.godigit.com/docs",
                "category": "travel_insurance",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "digit_...",
                "base_url": "https://api.godigit.com/v1",
                "features": ["get_quote", "policy_purchase", "claim_filing", "coverage_check"],
                "powered_by_tagline": "Powered by Go Digit in Association with We Hive",
            },
            {
                "id": "policybazaar",
                "name": "Policy Bazaar",
                "description": "India's largest insurance aggregator — compare and buy travel policies",
                "website": "https://policybazaar.com",
                "docs": "https://developer.policybazaar.com/docs",
                "category": "travel_insurance",
                "requires_key": True,
                "key_label": "Partner Token",
                "key_placeholder": "pb_...",
                "base_url": "https://api.policybazaar.com/v1",
                "features": ["quote_comparison", "policy_purchase", "claim_status"],
                "powered_by_tagline": "Powered by Policy Bazaar in Association with We Hive",
            },
        ],
    },
    {
        "id": "appt_slots",
        "name": "Appointment Slots Module",
        "description": "Monitor VFS Global and BLS appointment availability and notify users on slot opening",
        "services": [
            {
                "id": "vfsglobal",
                "name": "VFS Global",
                "description": "Track visa application appointment slots across 100+ visa centres globally",
                "website": "https://vfsglobal.com",
                "docs": "https://api.vfsglobal.com/docs",
                "category": "appt_slots",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "vfs_...",
                "base_url": "https://api.vfsglobal.com/v1",
                "features": ["slot_availability", "center_list", "slot_alert_subscription", "tracking"],
                "powered_by_tagline": "Powered by VFS Global in Association with We Hive",
            },
            {
                "id": "blsintl",
                "name": "BLS Intl",
                "description": "Track BLS visa application centre appointment slots in India and globally",
                "website": "https://blsglobal.com",
                "docs": "https://api.blsglobal.com/docs",
                "category": "appt_slots",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "bls_...",
                "base_url": "https://api.blsglobal.com/v1",
                "features": ["slot_availability", "center_locations", "slot_alerts", "status_check"],
                "powered_by_tagline": "Powered by BLS Intl in Association with We Hive",
            },
        ],
    },
]
