"""Third-party service integrations registry.

Categories:
- visa_apis:   Atlys, VisaHQ, iVisa  (real-time visa requirements)
- travel_booking: Skyscanner, Amadeus, Booking.com  (flights / hotels)
- payments_forex: Razorpay, Wise API, Stripe  (payments + FX rates)
- travel_insurance: Travelex, Go Digit, Policy Bazaar  (insurance quotes)
- appt_slots:  VFS Global, BLS Intl  (appointment slot monitoring)
- llm_providers: 50+ large language model, audio, and image inference APIs
- ai_frameworks: LiteLLM, LangChain Hub, Langfuse, Sentence-Transformers, etc.
- vector_dbs: Pinecone, Qdrant, MongoDB Atlas Vector Search
- mcp_external: External Model Context Protocol servers
- mcp_internal: Domain / internal HR and immigration MCP servers
"""

from __future__ import annotations

SERVICE_CATEGORIES = [
    {
        "id": "visa_apis",
        "name": "Visa APIs",
        "description": "Real-time visa requirements, document checklists, and application status",
        "services": [
            {
                "id": "atlys",
                "name": "Atlys",
                "description": "Visa requirements by country pair — rules, documents, fees, timelines",
                "website": "https://atlys.com",
                "docs": "https://docs.atlys.com",
                "category": "visa_apis",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "atlys_...",
                "base_url": "https://api.atlys.com/v1",
                "features": ["visa_requirements", "document_checklist", "country_rules", "fee_schedule"],
                "powered_by_tagline": "Powered by Atlys in Association with We Hive",
            },
            {
                "id": "visahq",
                "name": "VisaHQ",
                "description": "Visa application support and requirements for 200+ countries",
                "website": "https://visahq.com",
                "docs": "https://visahq.com/api/docs",
                "category": "visa_apis",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "vq_...",
                "base_url": "https://api.visahq.com/v1",
                "features": ["visa_requirements", "application_form", "status_tracking"],
                "powered_by_tagline": "Powered by VisaHQ in Association with We Hive",
            },
            {
                "id": "ivisa",
                "name": "iVisa",
                "description": "Fast-track visa applications and real-time status tracking",
                "website": "https://ivisa.com",
                "docs": "https://ivisa.com/developers",
                "category": "visa_apis",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "iv_...",
                "base_url": "https://api.ivisa.com/v1",
                "features": ["visa_application", "status_tracking", "document_review"],
                "powered_by_tagline": "Powered by iVisa in Association with We Hive",
            },
        ],
    },
    {
        "id": "travel_booking",
        "name": "Travel Booking",
        "description": "Flight and hotel search, pricing, and booking — convert planning into bookings",
        "services": [
            {
                "id": "skyscanner",
                "name": "Skyscanner",
                "description": "Flight and hotel search API with live pricing from 1,200+ travel sites",
                "website": "https://skyscanner.com",
                "docs": "https://developers.skyscanner.net",
                "category": "travel_booking",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "skyscanner_...",
                "base_url": "https://skyscanner-provider-api.com/v1",
                "features": ["flight_search", "hotel_search", "price_comparison", "booking_link"],
                "powered_by_tagline": "Powered by Skyscanner in Association with We Hive",
            },
            {
                "id": "amadeus",
                "name": "Amadeus",
                "description": "Professional travel APIs — flight search, booking, NDC, schedule and hotel",
                "website": "https://amadeus.com",
                "docs": "https://developers.amadeus.com",
                "category": "travel_booking",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "amadeus_...",
                "base_url": "https://test.api.amadeus.com/v2",
                "features": ["flight_search", "flight_booking", "hotel_search", "seat_maps", "tourist_insights"],
                "powered_by_tagline": "Powered by Amadeus in Association with We Hive",
            },
            {
                "id": "bookingcom",
                "name": "Booking.com",
                "description": "Hotel inventory, availability and booking integration",
                "website": "https://booking.com",
                "docs": "https://www.booking.com/developer/apiphp.html",
                "category": "travel_booking",
                "requires_key": True,
                "key_label": "Affiliate PID",
                "key_placeholder": "booking_...",
                "base_url": "https://supply-xml.booking.com/hotels-api",
                "features": ["hotel_search", "availability", "booking", "review_stars"],
                "powered_by_tagline": "Powered by Booking.com in Association with We Hive",
            },
        ],
    },
    {
        "id": "payments_forex",
        "name": "Payments and Forex",
        "description": "Accept visa fee payments and live currency exchange rates for budgeting",
        "services": [
            {
                "id": "razorpay",
                "name": "Razorpay",
                "description": "Accept visa fee payments — cards, UPI, net banking, wallets",
                "website": "https://razorpay.com",
                "docs": "https://razorpay.com/docs/",
                "category": "payments_forex",
                "requires_key": True,
                "key_label": "Key ID",
                "key_placeholder": "rzp_...",
                "base_url": "https://api.razorpay.com/v1",
                "features": ["payment_gateway", "upi", "cards", "wallets", "webhook"],
                "powered_by_tagline": "Powered by Razorpay in Association with We Hive",
            },
            {
                "id": "wise",
                "name": "Wise API",
                "description": "Live mid-market exchange rates and international transfers",
                "website": "https://wise.com",
                "docs": "https://wise.com/docs",
                "category": "payments_forex",
                "requires_key": True,
                "key_label": "API Token",
                "key_placeholder": "wise_...",
                "base_url": "https://api.wise.com/v1",
                "features": ["exchange_rates", "currency_conversion", "transfer_tracking"],
                "powered_by_tagline": "Powered by Wise in Association with We Hive",
            },
            {
                "id": "stripe",
                "name": "Stripe",
                "description": "Global payment processing — cards, Apple Pay, Google Pay, SEPA",
                "website": "https://stripe.com",
                "docs": "https://stripe.com/docs/developers",
                "category": "payments_forex",
                "requires_key": True,
                "key_label": "Secret Key",
                "key_placeholder": "sk_...",
                "base_url": "https://api.stripe.com/v1",
                "features": ["payment_gateway", "invoicing", "subscriptions", "fx_conversion"],
                "powered_by_tagline": "Powered by Stripe in Association with We Hive",
            },
        ],
    },
    {
        "id": "travel_insurance",
        "name": "Travel Insurance",
        "description": "Embed insurance quotes and purchase flows — required for Schengen and UK visas",
        "services": [
            {
                "id": "travelex",
                "name": "Travelex",
                "description": "International travel insurance policies with instant online purchase",
                "website": "https://travelex.com",
                "docs": "https://api.travelex.com/docs",
                "category": "travel_insurance",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "travelex_...",
                "base_url": "https://api.travelex.com/v1",
                "features": ["get_quote", "policy_purchase", "claim_status", "coverage_details"],
                "powered_by_tagline": "Powered by Travelex in Association with We Hive",
            },
            {
                "id": "godigit",
                "name": "Go Digit",
                "description": "Digital-first travel insurance — comprehensive, affordable, fast claims",
                "website": "https://godigit.com",
                "docs": "https://api.godigit.com/docs",
                "category": "travel_insurance",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "digit_...",
                "base_url": "https://api.godigit.com/v1",
                "features": ["get_quote", "policy_purchase", "claim_filing", "coverage_check"],
                "powered_by_tagline": "Powered by Go Digit in Association with We Hive",
            },
            {
                "id": "policybazaar",
                "name": "Policy Bazaar",
                "description": "India's largest insurance aggregator — compare and buy travel policies",
                "website": "https://policybazaar.com",
                "docs": "https://developer.policybazaar.com/docs",
                "category": "travel_insurance",
                "requires_key": True,
                "key_label": "Partner Token",
                "key_placeholder": "pb_...",
                "base_url": "https://api.policybazaar.com/v1",
                "features": ["quote_comparison", "policy_purchase", "claim_status"],
                "powered_by_tagline": "Powered by Policy Bazaar in Association with We Hive",
            },
        ],
    },
    {
        "id": "appt_slots",
        "name": "Appointment Slots Module",
        "description": "Monitor VFS Global and BLS appointment availability and notify users on slot opening",
        "services": [
            {
                "id": "vfsglobal",
                "name": "VFS Global",
                "description": "Track visa application appointment slots across 100+ visa centres globally",
                "website": "https://vfsglobal.com",
                "docs": "https://api.vfsglobal.com/docs",
                "category": "appt_slots",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "vfs_...",
                "base_url": "https://api.vfsglobal.com/v1",
                "features": ["slot_availability", "center_list", "slot_alert_subscription", "tracking"],
                "powered_by_tagline": "Powered by VFS Global in Association with We Hive",
            },
            {
                "id": "blsintl",
                "name": "BLS Intl",
                "description": "Track BLS visa application centre appointment slots in India and globally",
                "website": "https://blsglobal.com",
                "docs": "https://api.blsglobal.com/docs",
                "category": "appt_slots",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "bls_...",
                "base_url": "https://api.blsglobal.com/v1",
                "features": ["slot_availability", "center_locations", "slot_alerts", "status_check"],
                "powered_by_tagline": "Powered by BLS Intl in Association with We Hive",
            },
        ],
    },
    # ---------------------------------------------------------------------------
    # AI / LLM providers
    # ---------------------------------------------------------------------------
    {
        "id": "llm_providers",
        "name": "LLM Providers",
        "description": "Large language model, audio, and image inference APIs for Eva and agentic features",
        "services": [
            {
                "id": "openai",
                "name": "OpenAI",
                "description": "GPT-4o, GPT-4o-mini, embeddings, and vision models",
                "website": "https://openai.com",
                "docs": "https://platform.openai.com/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-...",
                "base_url": "https://api.openai.com/v1",
                "features": ["chat", "completions", "embeddings", "vision"],
                "powered_by_tagline": "Powered by OpenAI in Association with We Hive",
            },
            {
                "id": "anthropic",
                "name": "Anthropic",
                "description": "Claude family of models via the Anthropic API",
                "website": "https://anthropic.com",
                "docs": "https://docs.anthropic.com",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-ant-...",
                "base_url": "https://api.anthropic.com/v1",
                "features": ["chat", "reasoning", "vision", "tool_use"],
                "powered_by_tagline": "Powered by Anthropic in Association with We Hive",
            },
            {
                "id": "google_gemini",
                "name": "Google Gemini",
                "description": "Gemini 2.5 Pro / Flash and other Google AI models",
                "website": "https://ai.google.dev",
                "docs": "https://ai.google.dev/gemini-api/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "AIza...",
                "base_url": "https://generativelanguage.googleapis.com/v1beta",
                "features": ["chat", "vision", "embeddings", "long_context"],
                "powered_by_tagline": "Powered by Google Gemini in Association with We Hive",
            },
            {
                "id": "groq",
                "name": "Groq",
                "description": "Ultra-fast inference for open-source models and Whisper transcription",
                "website": "https://groq.com",
                "docs": "https://console.groq.com/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "gsk_...",
                "base_url": "https://api.groq.com/openai/v1",
                "features": ["fast_inference", "chat", "transcription"],
                "powered_by_tagline": "Powered by Groq in Association with We Hive",
            },
            {
                "id": "deepseek",
                "name": "DeepSeek",
                "description": "DeepSeek Chat and Coder open-weight models",
                "website": "https://deepseek.com",
                "docs": "https://platform.deepseek.com/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-...",
                "base_url": "https://api.deepseek.com/v1",
                "features": ["chat", "coding", "reasoning"],
                "powered_by_tagline": "Powered by DeepSeek in Association with We Hive",
            },
            {
                "id": "cerebras",
                "name": "Cerebras",
                "description": "Wafer-scale ultra-fast inference with generous free tier",
                "website": "https://cerebras.ai",
                "docs": "https://inference-docs.cerebras.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "csk-...",
                "base_url": "https://api.cerebras.ai/v1",
                "features": ["fast_inference", "chat"],
                "powered_by_tagline": "Powered by Cerebras in Association with We Hive",
            },
            {
                "id": "mistral",
                "name": "Mistral AI",
                "description": "Mistral's own API for open-weight and commercial models",
                "website": "https://mistral.ai",
                "docs": "https://docs.mistral.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.mistral.ai/v1",
                "features": ["chat", "embeddings", "function_calling"],
                "powered_by_tagline": "Powered by Mistral AI in Association with We Hive",
            },
            {
                "id": "openrouter",
                "name": "OpenRouter",
                "description": "Access 200+ models through a single OpenAI-compatible endpoint",
                "website": "https://openrouter.ai",
                "docs": "https://openrouter.ai/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-or-...",
                "base_url": "https://openrouter.ai/api/v1",
                "features": ["model_aggregator", "chat", "routing"],
                "powered_by_tagline": "Powered by OpenRouter in Association with We Hive",
            },
            {
                "id": "huggingface",
                "name": "Hugging Face",
                "description": "Inference API for thousands of open-source models",
                "website": "https://huggingface.co",
                "docs": "https://huggingface.co/docs/api-inference/index",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "HF Token",
                "key_placeholder": "hf_...",
                "base_url": "https://api-inference.huggingface.co/models",
                "features": ["inference_api", "embeddings", "models"],
                "powered_by_tagline": "Powered by Hugging Face in Association with We Hive",
            },
            {
                "id": "together",
                "name": "Together AI",
                "description": "Fast inference for open-source models at scale",
                "website": "https://together.ai",
                "docs": "https://docs.together.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "tgp_...",
                "base_url": "https://api.together.xyz/v1",
                "features": ["chat", "fine_tuning", "inference"],
                "powered_by_tagline": "Powered by Together AI in Association with We Hive",
            },
            {
                "id": "perplexity",
                "name": "Perplexity",
                "description": "Online LLM with real-time search and citations",
                "website": "https://perplexity.ai",
                "docs": "https://docs.perplexity.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "pplx-...",
                "base_url": "https://api.perplexity.ai",
                "features": ["online_search", "chat", "citations"],
                "powered_by_tagline": "Powered by Perplexity in Association with We Hive",
            },
            {
                "id": "cohere",
                "name": "Cohere",
                "description": "Command and Embed models via the Cohere API",
                "website": "https://cohere.com",
                "docs": "https://docs.cohere.com",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.cohere.com/v1",
                "features": ["chat", "embeddings", "rerank"],
                "powered_by_tagline": "Powered by Cohere in Association with We Hive",
            },
            {
                "id": "nvidia",
                "name": "NVIDIA",
                "description": "NVIDIA NIM inference microservices for Llama, Nemotron, and more",
                "website": "https://nvidia.com",
                "docs": "https://docs.api.nvidia.com",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "nvapi-...",
                "base_url": "https://integrate.api.nvidia.com/v1",
                "features": ["nim_inference", "chat", "embeddings"],
                "powered_by_tagline": "Powered by NVIDIA in Association with We Hive",
            },
            {
                "id": "fireworks",
                "name": "Fireworks AI",
                "description": "Enterprise-ready fast inference for compound AI systems",
                "website": "https://fireworks.ai",
                "docs": "https://docs.fireworks.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "fw_...",
                "base_url": "https://api.fireworks.ai/inference/v1",
                "features": ["fast_inference", "chat", "compound_ai"],
                "powered_by_tagline": "Powered by Fireworks AI in Association with We Hive",
            },
            {
                "id": "xai",
                "name": "xAI (Grok)",
                "description": "Grok models with real-time web search and reasoning",
                "website": "https://x.ai",
                "docs": "https://docs.x.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "xai-...",
                "base_url": "https://api.x.ai/v1",
                "features": ["chat", "reasoning", "real_time"],
                "powered_by_tagline": "Powered by xAI Grok in Association with We Hive",
            },
            {
                "id": "replicate",
                "name": "Replicate",
                "description": "Run and fine-tune open-source models in the cloud",
                "website": "https://replicate.com",
                "docs": "https://replicate.com/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Token",
                "key_placeholder": "r8_...",
                "base_url": "https://api.replicate.com/v1",
                "features": ["model_hosting", "fine_tuning", "image_video"],
                "powered_by_tagline": "Powered by Replicate in Association with We Hive",
            },
            {
                "id": "elevenlabs",
                "name": "ElevenLabs",
                "description": "High-quality text-to-speech and voice cloning",
                "website": "https://elevenlabs.io",
                "docs": "https://docs.elevenlabs.io",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk_...",
                "base_url": "https://api.elevenlabs.io/v1",
                "features": ["text_to_speech", "voice_cloning", "audio"],
                "powered_by_tagline": "Powered by ElevenLabs in Association with We Hive",
            },
            {
                "id": "assemblyai",
                "name": "AssemblyAI",
                "description": "Speech-to-text and audio intelligence",
                "website": "https://assemblyai.com",
                "docs": "https://www.assemblyai.com/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.assemblyai.com/v2",
                "features": ["speech_to_text", "audio_intelligence"],
                "powered_by_tagline": "Powered by AssemblyAI in Association with We Hive",
            },
            {
                "id": "deepgram",
                "name": "Deepgram",
                "description": "Fast, accurate speech-to-text and text-to-speech",
                "website": "https://deepgram.com",
                "docs": "https://developers.deepgram.com",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.deepgram.com/v1",
                "features": ["speech_to_text", "text_to_speech"],
                "powered_by_tagline": "Powered by Deepgram in Association with We Hive",
            },
            {
                "id": "deepinfra",
                "name": "DeepInfra",
                "description": "Serverless inference for open-source LLMs and embeddings",
                "website": "https://deepinfra.com",
                "docs": "https://deepinfra.com/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.deepinfra.com/v1/openai",
                "features": ["serverless_inference", "chat", "embeddings"],
                "powered_by_tagline": "Powered by DeepInfra in Association with We Hive",
            },
            {
                "id": "novita",
                "name": "Novita AI",
                "description": "Fast, affordable inference for open-source models",
                "website": "https://novita.ai",
                "docs": "https://novita.ai/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.novita.ai/v3/openai",
                "features": ["chat", "image_generation"],
                "powered_by_tagline": "Powered by Novita AI in Association with We Hive",
            },
            {
                "id": "stability",
                "name": "Stability AI",
                "description": "Image and video generation models",
                "website": "https://stability.ai",
                "docs": "https://platform.stability.ai/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-...",
                "base_url": "https://api.stability.ai/v2beta",
                "features": ["image_generation", "video_generation"],
                "powered_by_tagline": "Powered by Stability AI in Association with We Hive",
            },
            {
                "id": "fal",
                "name": "Fal.ai",
                "description": "Fast image and video generation API",
                "website": "https://fal.ai",
                "docs": "https://fal.ai/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://fal.run",
                "features": ["image_generation", "video_generation"],
                "powered_by_tagline": "Powered by Fal.ai in Association with We Hive",
            },
            {
                "id": "ai21",
                "name": "AI21 Labs",
                "description": "Jamba models with long context windows",
                "website": "https://www.ai21.com",
                "docs": "https://docs.ai21.com",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "ai21-...",
                "base_url": "https://api.ai21.com/studio/v1",
                "features": ["chat", "long_context"],
                "powered_by_tagline": "Powered by AI21 Labs in Association with We Hive",
            },
            {
                "id": "moonshot",
                "name": "Kimi (Moonshot)",
                "description": "Kimi long-context models by Moonshot AI",
                "website": "https://moonshot.cn",
                "docs": "https://platform.moonshot.cn/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-...",
                "base_url": "https://api.moonshot.cn/v1",
                "features": ["long_context", "chat"],
                "powered_by_tagline": "Powered by Moonshot AI in Association with We Hive",
            },
            {
                "id": "lemonfox",
                "name": "Lemonfox",
                "description": "Open-source model inference with vision support",
                "website": "https://lemonfox.ai",
                "docs": "https://docs.lemonfox.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.lemonfox.ai/v1",
                "features": ["chat", "image_vision"],
                "powered_by_tagline": "Powered by Lemonfox in Association with We Hive",
            },
            {
                "id": "aionlabs",
                "name": "Aionlabs",
                "description": "Agent-focused inference platform",
                "website": "https://aionlabs.ai",
                "docs": "https://docs.aionlabs.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.aionlabs.ai/v1",
                "features": ["chat", "agents"],
                "powered_by_tagline": "Powered by Aionlabs in Association with We Hive",
            },
            {
                "id": "skillboss",
                "name": "Skillboss",
                "description": "Skill-oriented LLM API for domain tasks",
                "website": "https://skillboss.ai",
                "docs": "https://docs.skillboss.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.skillboss.ai/v1",
                "features": ["chat", "skills"],
                "powered_by_tagline": "Powered by Skillboss in Association with We Hive",
            },
            {
                "id": "alibaba_bailian",
                "name": "Alibaba Bailian",
                "description": "Qwen models via Alibaba Cloud Bailian / DashScope",
                "website": "https://bailian.aliyun.com",
                "docs": "https://help.aliyun.com/zh/dashscope",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-...",
                "base_url": "https://dashscope.aliyuncs.com/compatible-mode/v1",
                "features": ["qwen_models", "chat", "embeddings"],
                "powered_by_tagline": "Powered by Alibaba Bailian in Association with We Hive",
            },
            {
                "id": "zhipu",
                "name": "Zhipu AI",
                "description": "GLM series models from Zhipu AI",
                "website": "https://zhipu.ai",
                "docs": "https://open.bigmodel.cn/dev/howuse/glm-4",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://open.bigmodel.cn/api/paas/v4",
                "features": ["glm_models", "chat"],
                "powered_by_tagline": "Powered by Zhipu AI in Association with We Hive",
            },
            {
                "id": "cloudflare_workers_ai",
                "name": "Cloudflare Workers AI",
                "description": "Serverless inference on Cloudflare's global network",
                "website": "https://developers.cloudflare.com/workers-ai",
                "docs": "https://developers.cloudflare.com/workers-ai/models",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Token (account_id:token)",
                "key_placeholder": "...",
                "base_url": "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1",
                "features": ["serverless_inference", "chat", "embeddings"],
                "powered_by_tagline": "Powered by Cloudflare Workers AI in Association with We Hive",
            },
            {
                "id": "sambanova",
                "name": "SambaNova",
                "description": "Fast, affordable inference for enterprise open models",
                "website": "https://sambanova.ai",
                "docs": "https://docs.sambanova.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.sambanova.ai/v1",
                "features": ["enterprise_inference", "chat"],
                "powered_by_tagline": "Powered by SambaNova in Association with We Hive",
            },
            {
                "id": "ollama",
                "name": "Ollama (local)",
                "description": "Run open-source models locally — data never leaves the server",
                "website": "https://ollama.com",
                "docs": "https://github.com/ollama/ollama/blob/main/docs/api.md",
                "category": "llm_providers",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:11434",
                "base_url": "http://localhost:11434",
                "features": ["local_inference", "chat", "embeddings"],
                "powered_by_tagline": "Powered by Ollama in Association with We Hive",
            },
            {
                "id": "localai",
                "name": "LocalAI",
                "description": "Self-hosted OpenAI-compatible API for local models",
                "website": "https://localai.io",
                "docs": "https://localai.io/docs",
                "category": "llm_providers",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:8080/v1",
                "base_url": "http://localhost:8080/v1",
                "features": ["self_hosted", "openai_compatible"],
                "powered_by_tagline": "Powered by LocalAI in Association with We Hive",
            },
            {
                "id": "koboldai",
                "name": "KoboldAI",
                "description": "Self-hosted KoboldAI / KoboldCPP text generation endpoint",
                "website": "https://koboldai.net",
                "docs": "https://github.com/LostRuins/koboldcpp",
                "category": "llm_providers",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:5001/api/v1",
                "base_url": "http://localhost:5001/api/v1",
                "features": ["self_hosted", "text_generation"],
                "powered_by_tagline": "Powered by KoboldAI in Association with We Hive",
            },
            {
                "id": "vllm",
                "name": "vLLM (self-hosted)",
                "description": "Self-hosted OpenAI-compatible LLM inference with high throughput",
                "website": "https://vllm.ai",
                "docs": "https://docs.vllm.ai",
                "category": "llm_providers",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:8000/v1",
                "base_url": "http://localhost:8000/v1",
                "features": ["self_hosted", "openai_compatible", "throughput"],
                "powered_by_tagline": "Powered by vLLM in Association with We Hive",
            },
            {
                "id": "pollinations",
                "name": "Pollinations AI",
                "description": "Free, no-signup inference for open-source LLMs and images",
                "website": "https://pollinations.ai",
                "docs": "https://pollinations.ai/docs",
                "category": "llm_providers",
                "requires_key": False,
                "key_label": "Optional API Key",
                "key_placeholder": "...",
                "base_url": "https://text.pollinations.ai/openai",
                "features": ["free_inference", "chat", "image"],
                "powered_by_tagline": "Powered by Pollinations AI in Association with We Hive",
            },
            {
                "id": "kluster",
                "name": "Kluster",
                "description": "Open-source model inference and fine-tuning platform",
                "website": "https://kluster.ai",
                "docs": "https://docs.kluster.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.kluster.ai/v1",
                "features": ["chat", "fine_tuning"],
                "powered_by_tagline": "Powered by Kluster in Association with We Hive",
            },
            {
                "id": "llm7",
                "name": "LLM7",
                "description": "LLM routing and inference API",
                "website": "https://llm7.io",
                "docs": "https://docs.llm7.io",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.llm7.io/v1",
                "features": ["chat", "routing"],
                "powered_by_tagline": "Powered by LLM7 in Association with We Hive",
            },
            {
                "id": "glhf",
                "name": "GLHF",
                "description": "Open-source model chat API",
                "website": "https://glhf.chat",
                "docs": "https://docs.glhf.chat",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.glhf.chat/v1",
                "features": ["chat", "open_source_models"],
                "powered_by_tagline": "Powered by GLHF in Association with We Hive",
            },
            {
                "id": "kilocode",
                "name": "KiloCode",
                "description": "Coding-focused LLM API",
                "website": "https://kilocode.ai",
                "docs": "https://docs.kilocode.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.kilocode.ai/v1",
                "features": ["chat", "coding"],
                "powered_by_tagline": "Powered by KiloCode in Association with We Hive",
            },
            {
                "id": "ovhcloud",
                "name": "OVHcloud",
                "description": "OVHcloud AI Training and Inference services",
                "website": "https://ovhcloud.com",
                "docs": "https://docs.ovhcloud.com",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.ovh.com",
                "features": ["ai_training", "inference"],
                "powered_by_tagline": "Powered by OVHcloud in Association with We Hive",
            },
            {
                "id": "nscale",
                "name": "nScale",
                "description": "nScale AI inference platform",
                "website": "https://nscale.com",
                "docs": "https://docs.nscale.com",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.nscale.com/v1",
                "features": ["ai_inference", "chat"],
                "powered_by_tagline": "Powered by nScale in Association with We Hive",
            },
            {
                "id": "nebius",
                "name": "Nebius AI Studio",
                "description": "GPU cloud inference for open-source models",
                "website": "https://studio.nebius.ai",
                "docs": "https://studio.nebius.ai/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.studio.nebius.ai/v1",
                "features": ["gpu_inference", "chat"],
                "powered_by_tagline": "Powered by Nebius AI Studio in Association with We Hive",
            },
            {
                "id": "chutes",
                "name": "Chutes",
                "description": "Decentralized AI inference network",
                "website": "https://chutes.ai",
                "docs": "https://docs.chutes.ai",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.chutes.ai/v1",
                "features": ["decentralized_inference", "chat"],
                "powered_by_tagline": "Powered by Chutes in Association with We Hive",
            },
            {
                "id": "modelscope",
                "name": "ModelScope",
                "description": "Model-as-a-Service hub for open-source Chinese and global models",
                "website": "https://modelscope.cn",
                "docs": "https://modelscope.cn/docs",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.modelscope.cn/v1",
                "features": ["model_hub", "chat", "inference"],
                "powered_by_tagline": "Powered by ModelScope in Association with We Hive",
            },
            {
                "id": "siliconflow",
                "name": "SiliconFlow",
                "description": "Fast inference platform for open-source models",
                "website": "https://siliconflow.cn",
                "docs": "https://docs.siliconflow.cn",
                "category": "llm_providers",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "sk-...",
                "base_url": "https://api.siliconflow.cn/v1",
                "features": ["fast_inference", "chat", "embeddings"],
                "powered_by_tagline": "Powered by SiliconFlow in Association with We Hive",
            },
        ],
    },
    # ---------------------------------------------------------------------------
    # AI frameworks and libraries
    # ---------------------------------------------------------------------------
    {
        "id": "ai_frameworks",
        "name": "AI Frameworks & Libraries",
        "description": "Orchestration, observability, tokenization, and embedding libraries",
        "services": [
            {
                "id": "litellm",
                "name": "LiteLLM",
                "description": "Unified LLM proxy and router for 100+ providers",
                "website": "https://litellm.ai",
                "docs": "https://docs.litellm.ai",
                "category": "ai_frameworks",
                "requires_key": True,
                "key_label": "Proxy API Key",
                "key_placeholder": "sk-...",
                "base_url": "https://api.litellm.ai",
                "features": ["proxy", "unified_api", "routing"],
                "powered_by_tagline": "Powered by LiteLLM in Association with We Hive",
            },
            {
                "id": "langchain_hub",
                "name": "LangChain (Hub)",
                "description": "Prompt hub, tracing, and evaluation via LangSmith",
                "website": "https://smith.langchain.com",
                "docs": "https://docs.smith.langchain.com",
                "category": "ai_frameworks",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "ls-...",
                "base_url": "https://api.smith.langchain.com",
                "features": ["prompt_hub", "tracing", "evaluation"],
                "powered_by_tagline": "Powered by LangChain in Association with We Hive",
            },
            {
                "id": "langfuse",
                "name": "Langfuse",
                "description": "LLM observability, tracing, and evaluation platform",
                "website": "https://langfuse.com",
                "docs": "https://langfuse.com/docs",
                "category": "ai_frameworks",
                "requires_key": True,
                "key_label": "Public Key",
                "key_placeholder": "pk-lf-...",
                "base_url": "https://cloud.langfuse.com",
                "features": ["observability", "tracing", "evals"],
                "powered_by_tagline": "Powered by Langfuse in Association with We Hive",
            },
            {
                "id": "sentence_transformers",
                "name": "Sentence-Transformers",
                "description": "Local embeddings for semantic search and RAG (no cloud key)",
                "website": "https://sbert.net",
                "docs": "https://sbert.net",
                "category": "ai_frameworks",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["local_embeddings", "semantic_search"],
                "powered_by_tagline": "Powered by Sentence-Transformers",
            },
            {
                "id": "tiktoken",
                "name": "TikToken",
                "description": "Fast OpenAI tokenizer for token counting and chunking",
                "website": "https://github.com/openai/tiktoken",
                "docs": "https://github.com/openai/tiktoken",
                "category": "ai_frameworks",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["token_counting", "encoding"],
                "powered_by_tagline": "Powered by TikToken",
            },
            {
                "id": "tokenizers",
                "name": "Tokenizers",
                "description": "Fast tokenization library from Hugging Face",
                "website": "https://huggingface.co/docs/tokenizers",
                "docs": "https://huggingface.co/docs/tokenizers",
                "category": "ai_frameworks",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["fast_tokenization", "preprocessing"],
                "powered_by_tagline": "Powered by Hugging Face Tokenizers",
            },
        ],
    },
    # ---------------------------------------------------------------------------
    # Vector DBs / RAG
    # ---------------------------------------------------------------------------
    {
        "id": "vector_dbs",
        "name": "Vector Databases / RAG",
        "description": "Vector stores and retrieval-augmented generation infrastructure",
        "services": [
            {
                "id": "pinecone",
                "name": "Pinecone",
                "description": "Managed vector database for semantic search and RAG",
                "website": "https://pinecone.io",
                "docs": "https://docs.pinecone.io",
                "category": "vector_dbs",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.pinecone.io",
                "features": ["vector_search", "rag", "indexing"],
                "powered_by_tagline": "Powered by Pinecone in Association with We Hive",
            },
            {
                "id": "qdrant",
                "name": "Qdrant",
                "description": "Open-source vector database with managed cloud option",
                "website": "https://qdrant.tech",
                "docs": "https://qdrant.tech/documentation",
                "category": "vector_dbs",
                "requires_key": True,
                "key_label": "API Key / URL",
                "key_placeholder": "...",
                "base_url": "https://api.qdrant.io",
                "features": ["vector_search", "rag", "hybrid"],
                "powered_by_tagline": "Powered by Qdrant in Association with We Hive",
            },
            {
                "id": "mongodb_atlas_vector_search",
                "name": "MongoDB Atlas Vector Search",
                "description": "Vector search built on MongoDB Atlas clusters",
                "website": "https://mongodb.com",
                "docs": "https://www.mongodb.com/docs/atlas/atlas-vector-search/",
                "category": "vector_dbs",
                "requires_key": True,
                "key_label": "Connection String",
                "key_placeholder": "mongodb+srv://...",
                "base_url": "https://cloud.mongodb.com",
                "features": ["vector_search", "atlas", "database"],
                "powered_by_tagline": "Powered by MongoDB Atlas in Association with We Hive",
            },
        ],
    },
    # ---------------------------------------------------------------------------
    # MCP servers (external)
    # ---------------------------------------------------------------------------
    {
        "id": "mcp_external",
        "name": "MCP Servers (External)",
        "description": "External Model Context Protocol servers for search, data, and productivity",
        "services": [
            {
                "id": "figma_mcp",
                "name": "Figma",
                "description": "Access Figma design files, components, and prototypes",
                "website": "https://figma.com",
                "docs": "https://www.figma.com/developers",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "Access Token",
                "key_placeholder": "...",
                "base_url": "https://api.figma.com",
                "features": ["design_files", "components", "prototypes"],
                "powered_by_tagline": "Powered by Figma in Association with We Hive",
            },
            {
                "id": "github_mcp",
                "name": "GitHub",
                "description": "Repository management, issues, PRs, and code search",
                "website": "https://github.com",
                "docs": "https://docs.github.com",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "Personal Access Token",
                "key_placeholder": "ghp_...",
                "base_url": "https://api.github.com",
                "features": ["repositories", "issues", "pull_requests", "code_search"],
                "powered_by_tagline": "Powered by GitHub in Association with We Hive",
            },
            {
                "id": "supabase_mcp",
                "name": "Supabase",
                "description": "PostgreSQL database, auth, and storage management",
                "website": "https://supabase.com",
                "docs": "https://supabase.com/docs",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "Service Role Key",
                "key_placeholder": "eyJ...",
                "base_url": "https://api.supabase.com",
                "features": ["database", "auth", "storage"],
                "powered_by_tagline": "Powered by Supabase in Association with We Hive",
            },
            {
                "id": "brave_search",
                "name": "Brave Search",
                "description": "Privacy-focused web search with AI summaries",
                "website": "https://brave.com/search",
                "docs": "https://brave.com/search/api/",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.search.brave.com",
                "features": ["web_search", "ai_summaries"],
                "powered_by_tagline": "Powered by Brave Search in Association with We Hive",
            },
            {
                "id": "tavily",
                "name": "Tavily",
                "description": "AI-optimized search API for RAG and agents",
                "website": "https://tavily.com",
                "docs": "https://docs.tavily.com",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "tvly-...",
                "base_url": "https://api.tavily.com",
                "features": ["search", "rag_optimized"],
                "powered_by_tagline": "Powered by Tavily in Association with We Hive",
            },
            {
                "id": "firecrawl",
                "name": "Firecrawl",
                "description": "Web scraping and crawling for LLM-ready content",
                "website": "https://firecrawl.dev",
                "docs": "https://docs.firecrawl.dev",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "fc-...",
                "base_url": "https://api.firecrawl.dev",
                "features": ["scrape", "crawl", "extract"],
                "powered_by_tagline": "Powered by Firecrawl in Association with We Hive",
            },
            {
                "id": "serper",
                "name": "Serper",
                "description": "Google Search API for LLMs",
                "website": "https://serper.dev",
                "docs": "https://serper.dev/docs",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://google.serper.dev",
                "features": ["google_search", "news", "images"],
                "powered_by_tagline": "Powered by Serper in Association with We Hive",
            },
            {
                "id": "searxng",
                "name": "SearXNG",
                "description": "Self-hosted meta-search engine",
                "website": "https://github.com/searxng/searxng",
                "docs": "https://docs.searxng.org",
                "category": "mcp_external",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:8080",
                "base_url": "http://localhost:8080",
                "features": ["meta_search", "self_hosted"],
                "powered_by_tagline": "Powered by SearXNG",
            },
            {
                "id": "jina_ai",
                "name": "Jina AI",
                "description": "URL-to-markdown and embedding reader",
                "website": "https://jina.ai",
                "docs": "https://jina.ai/docs",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://r.jina.ai",
                "features": ["reader", "embeddings", "search"],
                "powered_by_tagline": "Powered by Jina AI in Association with We Hive",
            },
            {
                "id": "exa",
                "name": "Exa",
                "description": "Semantic search engine for AI applications",
                "website": "https://exa.ai",
                "docs": "https://docs.exa.ai",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.exa.ai",
                "features": ["semantic_search", "similar", "contents"],
                "powered_by_tagline": "Powered by Exa in Association with We Hive",
            },
            {
                "id": "notion",
                "name": "Notion",
                "description": "Knowledge base, wiki, and project management",
                "website": "https://notion.so",
                "docs": "https://developers.notion.com",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "Integration Token",
                "key_placeholder": "secret_...",
                "base_url": "https://api.notion.com/v1",
                "features": ["pages", "databases", "wikis"],
                "powered_by_tagline": "Powered by Notion in Association with We Hive",
            },
            {
                "id": "slack_mcp",
                "name": "Slack",
                "description": "Team messaging, channels, and file sharing",
                "website": "https://slack.com",
                "docs": "https://api.slack.com",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "Bot User OAuth Token",
                "key_placeholder": "xoxb-...",
                "base_url": "https://slack.com/api",
                "features": ["messaging", "channels", "files"],
                "powered_by_tagline": "Powered by Slack in Association with We Hive",
            },
            {
                "id": "huggingface_mcp",
                "name": "HuggingFace",
                "description": "Access HuggingFace models, datasets, and spaces",
                "website": "https://huggingface.co",
                "docs": "https://huggingface.co/docs",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "HF Token",
                "key_placeholder": "hf_...",
                "base_url": "https://huggingface.co",
                "features": ["models", "datasets", "spaces"],
                "powered_by_tagline": "Powered by HuggingFace in Association with We Hive",
            },
            {
                "id": "google_knowledge_graph",
                "name": "Google Knowledge Graph",
                "description": "Structured entity data from Google Knowledge Graph",
                "website": "https://developers.google.com/knowledge-graph",
                "docs": "https://developers.google.com/knowledge-graph/reference/rest/v1",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "AIza...",
                "base_url": "https://kgsearch.googleapis.com",
                "features": ["entity_search", "knowledge_graph"],
                "powered_by_tagline": "Powered by Google Knowledge Graph in Association with We Hive",
            },
            {
                "id": "browserbase",
                "name": "Browserbase",
                "description": "Cloud headless browser automation",
                "website": "https://browserbase.com",
                "docs": "https://docs.browserbase.com",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.browserbase.com",
                "features": ["browser", "automation", "scraping"],
                "powered_by_tagline": "Powered by Browserbase in Association with We Hive",
            },
            {
                "id": "bright_data",
                "name": "Bright Data",
                "description": "Enterprise proxy and web data collection platform",
                "website": "https://brightdata.com",
                "docs": "https://docs.brightdata.com",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.brightdata.com",
                "features": ["proxy", "web_data", "scraping"],
                "powered_by_tagline": "Powered by Bright Data in Association with We Hive",
            },
            {
                "id": "scrapingbee",
                "name": "ScrapingBee",
                "description": "Web scraping API with proxy rotation and headless browser support",
                "website": "https://scrapingbee.com",
                "docs": "https://www.scrapingbee.com/docs",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://app.scrapingbee.com",
                "features": ["scraping", "proxy", "browser"],
                "powered_by_tagline": "Powered by ScrapingBee in Association with We Hive",
            },
            {
                "id": "funasr",
                "name": "FUNASR",
                "description": "End-to-end speech recognition toolkit",
                "website": "https://github.com/alibaba-damo-academy/FunASR",
                "docs": "https://github.com/alibaba-damo-academy/FunASR",
                "category": "mcp_external",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:10095",
                "base_url": "http://localhost:10095",
                "features": ["speech_recognition", "self_hosted"],
                "powered_by_tagline": "Powered by FUNASR",
            },
            {
                "id": "gpt_researcher",
                "name": "GPT Researcher",
                "description": "Autonomous multi-step research agent",
                "website": "https://gpt-researcher.synthagi.com",
                "docs": "https://docs.gptr.dev",
                "category": "mcp_external",
                "requires_key": True,
                "key_label": "API Key / TAVILY Key",
                "key_placeholder": "...",
                "base_url": "https://api.gptr.dev",
                "features": ["research", "reports", "multi_step"],
                "powered_by_tagline": "Powered by GPT Researcher in Association with We Hive",
            },
        ],
    },
    # ---------------------------------------------------------------------------
    # MCP servers (domain / internal)
    # ---------------------------------------------------------------------------
    {
        "id": "mcp_internal",
        "name": "MCP Servers (Domain / Internal)",
        "description": "Internal HR, immigration, and privacy-focused Model Context Protocol servers",
        "services": [
            {
                "id": "hyra_tools",
                "name": "Hyra Tools",
                "description": "Internal We Hive tools and platform utilities",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["internal_tools", "platform"],
                "powered_by_tagline": "Powered by Hyra Tools",
            },
            {
                "id": "immigration_tools",
                "name": "Immigration Tools",
                "description": "Visa, embassy, and immigration-specific data tools",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["visa", "embassy", "immigration"],
                "powered_by_tagline": "Powered by Immigration Tools",
            },
            {
                "id": "employee_tools",
                "name": "Employee Tools",
                "description": "Employee directory, org chart, and profile lookups",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["directory", "org_chart", "profiles"],
                "powered_by_tagline": "Powered by Employee Tools",
            },
            {
                "id": "payroll_tools",
                "name": "Payroll Tools",
                "description": "Payroll calculations, payslips, and salary data",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["payroll", "payslips", "salary"],
                "powered_by_tagline": "Powered by Payroll Tools",
            },
            {
                "id": "timeoff_tools",
                "name": "Timeoff Tools",
                "description": "Leave balances, time-off requests, and holiday calendars",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["leave", "time_off", "holidays"],
                "powered_by_tagline": "Powered by Timeoff Tools",
            },
            {
                "id": "hr_agent",
                "name": "HR Agent",
                "description": "HR policy agent for compliance and employee queries",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["policy", "compliance", "employee_qa"],
                "powered_by_tagline": "Powered by HR Agent",
            },
            {
                "id": "bamboohr",
                "name": "BambooHR",
                "description": "BambooHR HRIS integration for employee data and PTO",
                "website": "https://bamboohr.com",
                "docs": "https://documentation.bamboohr.com",
                "category": "mcp_internal",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.bamboohr.com/api/gateway.php",
                "features": ["employee_data", "pto", "hris"],
                "powered_by_tagline": "Powered by BambooHR in Association with We Hive",
            },
            {
                "id": "greenhouse",
                "name": "Greenhouse",
                "description": "Greenhouse ATS integration for recruiting and candidates",
                "website": "https://greenhouse.io",
                "docs": "https://developers.greenhouse.io",
                "category": "mcp_internal",
                "requires_key": True,
                "key_label": "Harvest API Key",
                "key_placeholder": "...",
                "base_url": "https://harvest.greenhouse.io/v1",
                "features": ["ats", "candidates", "jobs"],
                "powered_by_tagline": "Powered by Greenhouse in Association with We Hive",
            },
            {
                "id": "checkr",
                "name": "Checkr",
                "description": "Background checks and candidate screening",
                "website": "https://checkr.com",
                "docs": "https://docs.checkr.com",
                "category": "mcp_internal",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.checkr.com",
                "features": ["background_checks", "screening"],
                "powered_by_tagline": "Powered by Checkr in Association with We Hive",
            },
            {
                "id": "rchilli",
                "name": "RChilli",
                "description": "AI-powered resume parsing and candidate matching",
                "website": "https://rchilli.com",
                "docs": "https://docs.rchilli.com",
                "category": "mcp_internal",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.rchilli.com",
                "features": ["resume_parsing", "candidate_matching"],
                "powered_by_tagline": "Powered by RChilli in Association with We Hive",
            },
            {
                "id": "cognee",
                "name": "COGNEE",
                "description": "Agent memory and knowledge graph construction",
                "website": "https://cognee.ai",
                "docs": "https://docs.cognee.ai",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:8000",
                "base_url": "http://localhost:8000",
                "features": ["memory", "knowledge_graph"],
                "powered_by_tagline": "Powered by COGNEE",
            },
            {
                "id": "graphiti",
                "name": "GRAPHITI",
                "description": "Temporal knowledge graph for entity relationships",
                "website": "https://graphiti.ai",
                "docs": "https://docs.graphiti.ai",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "Base URL",
                "key_placeholder": "http://localhost:8000",
                "base_url": "http://localhost:8000",
                "features": ["knowledge_graph", "temporal"],
                "powered_by_tagline": "Powered by GRAPHITI",
            },
            {
                "id": "minthcm",
                "name": "MINTHCM",
                "description": "Open-source HR management system",
                "website": "https://minthcm.org",
                "docs": "https://docs.minthcm.org",
                "category": "mcp_internal",
                "requires_key": True,
                "key_label": "API Key",
                "key_placeholder": "...",
                "base_url": "https://api.minthcm.org",
                "features": ["hrms", "employees", "leave"],
                "powered_by_tagline": "Powered by MINTHCM in Association with We Hive",
            },
            {
                "id": "bias_detector",
                "name": "Bias Detector",
                "description": "Detect and mitigate bias in AI outputs and hiring",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["bias_detection", "compliance"],
                "powered_by_tagline": "Powered by Bias Detector",
            },
            {
                "id": "pseudonym",
                "name": "Pseudonym",
                "description": "Data pseudonymization and anonymization for privacy",
                "website": "https://wehive.io",
                "docs": "https://docs.wehive.io",
                "category": "mcp_internal",
                "requires_key": False,
                "key_label": "",
                "key_placeholder": "",
                "base_url": "",
                "features": ["pseudonymization", "privacy", "anonymization"],
                "powered_by_tagline": "Powered by Pseudonym",
            },
        ],
    },
]
